-- Test-only isolated schema derived from live column inventory 2026-09-27; no production data.
create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function auth.role() returns text language sql stable as $$select nullif(current_setting('request.jwt.claim.role',true),'')$$;
create table public.provider_profiles("id" uuid default gen_random_uuid(),"user_profile_id" uuid,"provider_type" text,"business_name" text,"description" text,"phone" text,"email" text,"location_text" text,"location_lat" double precision,"location_lng" double precision,"coverage_radius_km" double precision default 10.0,"specializations" text[] default '{}'::text[],"certifications" jsonb default '[]'::jsonb,"operating_hours" jsonb default '{}'::jsonb,"is_verified" boolean default false,"is_active" boolean default true,"status" text default 'pending'::text,"version" integer default 1,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now());
create table public.ride_cancellations("trip_id" uuid,"actor_id" uuid,"reason_code" text,"detail" text,"requires_safety_review" boolean,"automatic_fee_minor" bigint default 0,"created_at" timestamp with time zone default now());
create table public.ride_commission_calculations("id" uuid default gen_random_uuid(),"trip_id" uuid,"calculation_kind" text,"idempotency_key" text,"commission_policy_version" text,"commission_basis_points" integer,"commissionable_base_minor" bigint,"commission_amount_minor" bigint,"rounding_mode" text,"currency" text,"calculated_at" timestamp with time zone default now(),"settled_at" timestamp with time zone,"metadata" jsonb default '{}'::jsonb,"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid);
create table public.ride_commission_reservations("trip_id" uuid,"driver_id" uuid,"amount_minor" bigint,"currency" text,"state" text,"reserve_idempotency_key" text,"settlement_idempotency_key" text,"created_at" timestamp with time zone default now(),"settled_at" timestamp with time zone,"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid);
create table public.ride_driver_vehicles("id" uuid default gen_random_uuid(),"driver_id" uuid,"vehicle_id" text,"display_name" text,"seats" integer,"verification_status" text default 'PENDING'::text,"is_active" boolean default false,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now(),"verification_method" text default 'LEGACY_REVIEW'::text,"document_review_status" text default 'UNDER_REVIEW'::text,"evidence_manifest_sha256" text,"pilot_access_expires_at" timestamp with time zone,"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid,"make" text,"model" text,"model_year" integer,"color" text,"plate_masked" text,"fleet_name" text);
create table public.ride_fare_quotes("id" uuid default gen_random_uuid(),"trip_id" uuid,"quote_version" bigint,"currency" text,"transport_fare_minor" bigint,"approved_wait_minor" bigint default 0,"approved_stops_minor" bigint default 0,"approved_surcharges_minor" bigint default 0,"collected_cancellation_fee_minor" bigint default 0,"driver_funded_discount_minor" bigint default 0,"refunded_transport_minor" bigint default 0,"tip_minor" bigint default 0,"tolls_minor" bigint default 0,"taxes_minor" bigint default 0,"platform_promotion_minor" bigint default 0,"created_by" uuid,"accepted_by" uuid,"supersedes_quote_id" uuid,"idempotency_key" text,"payload_version" integer default 1,"accepted_at" timestamp with time zone default now(),"created_at" timestamp with time zone default now(),"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid);
create table public.ride_ledger_postings("id" uuid default gen_random_uuid(),"transaction_id" uuid,"entry_sequence" smallint,"account_code" text,"account_owner_id" uuid,"direction" text,"amount_minor" bigint,"currency" text,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now());
create table public.ride_ledger_transactions("id" uuid default gen_random_uuid(),"idempotency_key" text,"event_type" text,"trip_id" uuid,"currency" text,"reversal_of" uuid,"commission_policy_version" text,"commission_basis_points" integer,"commissionable_base_minor" bigint,"commission_amount_minor" bigint,"rounding_mode" text,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now(),"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid);
create table public.ride_offers("id" uuid default gen_random_uuid(),"request_id" uuid,"driver_id" uuid,"vehicle_id" uuid,"fare_minor" bigint,"currency" text,"eta_seconds" integer,"state" text default 'PENDING'::text,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now(),"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid);
create table public.ride_operational_holds("id" uuid default gen_random_uuid(),"trip_id" uuid,"hold_type" text,"reason_code" text,"requested_by" uuid,"source_state" text,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now(),"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid);
create table public.ride_requests("id" uuid,"passenger_id" uuid,"assigned_driver_id" uuid,"assigned_vehicle_id" uuid,"pickup_latitude" double precision,"pickup_longitude" double precision,"pickup_address" text,"destination_latitude" double precision,"destination_longitude" double precision,"destination_address" text,"offered_fare_minor" bigint,"final_fare_minor" bigint,"currency" text,"state" text default 'SEARCHING'::text,"version" bigint default 1,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now(),"completed_at" timestamp with time zone,"cancelled_at" timestamp with time zone,"payment_method" text,"quote_version" bigint default 1,"route_preference" text,"fare_breakdown" jsonb default '{}'::jsonb,"tenant_id" uuid default '00000000-0000-0000-0000-00000000e1a1'::uuid,"fare_mode" text default 'OPEN_BID'::text,"distance_rate_minor_per_km" bigint default 0,"time_rate_minor_per_minute" bigint default 0,"estimated_distance_meters" bigint default 0,"estimated_duration_seconds" bigint default 0,"estimated_fare_minor" bigint default 0,"fare_rate_card_version" bigint default 1,"allows_in_trip_stops" boolean default false,"ride_request_id" uuid,"rider_id" uuid,"market_id" text,"service_category_id" text,"dispatch_mode" text,"pickup_location" text,"pickup_accuracy_meters" real,"destination_location" text,"destination_accuracy_meters" real,"requested_price_minor" bigint,"currency_code" text,"scheduled_for" timestamp with time zone,"correlation_id" uuid,"dispatch_expires_at" timestamp with time zone default (clock_timestamp() + '00:30:00'::interval),"preferred_driver_id" uuid,"preferred_driver_invited_at" timestamp with time zone,"driver_rejection_count" integer default 0,"route_version" bigint default 1,"environment" text,"state_version" bigint default 1,"driver_arrived_at" timestamp with time zone);
create table public.ride_trip_events("id" bigint,"trip_id" uuid,"actor_id" uuid,"event_type" text,"from_state" text,"to_state" text,"payload" jsonb default '{}'::jsonb,"idempotency_key" text,"created_at" timestamp with time zone default now());
create table public.ride_wallet_ledger("id" uuid default gen_random_uuid(),"driver_id" uuid,"idempotency_key" text,"entry_type" text,"amount_minor" bigint,"currency" text,"direction" text,"trip_id" uuid,"withdrawable" boolean default false,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now());
create table public.ride_wallet_policy("policy_id" boolean default true,"currency" text default 'CRC'::text,"starter_credit_minor" bigint default 1500000,"commission_basis_points" integer default 500,"sinpe_phone" text default '63194029'::text,"sinpe_recipient_name" text default 'Jorge David Del Valle Miranda'::text,"updated_at" timestamp with time zone default now());
create table public.ride_wallets("driver_id" uuid,"currency" text,"created_at" timestamp with time zone default now(),"environment" text);
create table public.service_provider_wallet_ledger("id" uuid default gen_random_uuid(),"provider_id" text,"idempotency_key" text,"entry_type" text,"amount_minor" bigint,"currency" text default 'CRC'::text,"direction" text,"reference_id" text,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now());
create table public.service_provider_wallets("provider_id" text,"user_id" uuid,"business_name" text default 'Proveedor de Servicios'::text,"category" text default 'AUTOMOTIVE_MECHANIC'::text,"balance_minor" bigint default 5000,"currency" text default 'CRC'::text,"status" text default 'ACTIVE'::text,"min_balance_threshold_minor" bigint default 500,"commission_bps" bigint default 500,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now());
create table public.universal_service_offers("id" uuid default gen_random_uuid(),"request_id" uuid,"provider_id" uuid,"price_minor" bigint,"currency" text,"eta_minutes" integer,"warranty_days" integer default 0,"scope" jsonb default '{}'::jsonb,"state" text default 'PENDING'::text,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now());
create table public.universal_service_requests("id" uuid default gen_random_uuid(),"client_id" uuid,"service_definition_id" text,"modality" text,"title" text,"description" text,"intake" jsonb default '{}'::jsonb,"location" text,"location_label" text,"offered_price_minor" bigint,"final_price_minor" bigint,"currency" text,"state" text default 'OPEN'::text,"assigned_provider_id" uuid,"accepted_offer_id" uuid,"payment_state" text default 'NOT_STARTED'::text,"version" bigint default 1,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now());
create table public.user_profiles("id" uuid default gen_random_uuid(),"auth_user_id" uuid,"display_name" text default ''::text,"avatar_url" text,"phone_hash" text,"primary_role" text default 'driver'::text,"experience_level" text default 'basic'::text,"locale" text default 'es'::text,"timezone" text default 'America/Panama'::text,"consent_analytics" boolean default false,"consent_location" boolean default false,"consent_telemetry" boolean default false,"consent_marketing" boolean default false,"terms_accepted_at" timestamp with time zone,"privacy_accepted_at" timestamp with time zone,"account_status" text default 'active'::text,"metadata" jsonb default '{}'::jsonb,"created_at" timestamp with time zone default now(),"updated_at" timestamp with time zone default now());
alter table ride_wallets add primary key(driver_id);
alter table ride_wallet_policy add primary key(policy_id);
alter table ride_wallet_ledger add unique(idempotency_key);
alter table service_provider_wallets add primary key(provider_id);
alter table provider_profiles add primary key(id);
alter table user_profiles add primary key(id);
alter table ride_requests add primary key(id);
alter table ride_offers add unique(request_id,driver_id);
alter table ride_commission_reservations add primary key(trip_id);

CREATE OR REPLACE FUNCTION public.universal_service_provider_eligible_v1(p_actor uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
 select exists(select 1 from public.provider_profiles p
 join public.user_profiles u on u.id=p.user_profile_id
 where u.auth_user_id=p_actor and p.is_active and p.is_verified and p.status='active'
 and p.provider_type in ('service_provider','SERVICE_PROVIDER'));
$function$
;
