package com.elysium369.meet.core.memory

import kotlinx.serialization.Serializable

/**
 * ASTRA V6 §17, §69 — ELYSIUM MEMORY OS (Lifelong Second Brain).
 *
 * Architecture designed for longitudinal human memory spanning decades.
 * Provider-independent: can be backed by local SQLite, OpenClaw Memory-Wiki,
 * Supabase, or any future provider without losing accumulated knowledge.
 *
 * OpenClaw Integration (v2026.8+):
 * - Memory-Wiki structured claims → maps to [MemoryEntry] with evidence/freshness
 * - Contradiction detection → maps to [MemoryContradiction]
 * - Hybrid search (vector + keyword) → maps to [MemoryQuery]
 * - Per-agent isolation → maps to [MemoryNamespace]
 * - Dreaming/consolidation → maps to [MemoryConsolidationEvent]
 */

// ─── Memory Classification ───

enum class MemoryClass(val description: String) {
    IDENTITY("Quién soy, datos personales, preferencias fundamentales"),
    EPISODIC("Eventos vividos, experiencias, contextos"),
    SEMANTIC("Hechos conocidos, conceptos aprendidos, información general"),
    PROCEDURAL("Habilidades, cómo hacer cosas, recetas, workflows"),
    GOALS("Metas activas, planes, aspiraciones"),
    LEARNING("Progreso educativo, mastery states, conceptos por aprender"),
    MASTERY_EVIDENCE("Evidencia de competencia demostrada"),
    PROJECT_HISTORY("Proyectos activos y pasados, trabajo realizado"),
    ECONOMIC("Historial laboral, financiero, profesional"),
    PREFERENCES("Gustos, configuraciones, patrones de uso"),
    RELATIONAL("Conexiones con personas, empresas, instituciones"),
}

enum class MemoryConfidence {
    AUTHORITATIVE,  // Official document, verified measurement
    HIGH,           // Multiple consistent observations
    MODERATE,       // Single observation, no contradiction
    LOW,            // Inferred or reported without verification
    CONTESTED,      // Contradicted by newer evidence
    SUPERSEDED,     // Replaced by fresher entry
}

enum class MemoryProvenance {
    USER_EXPLICIT,        // User said "remember this"
    SYSTEM_OBSERVED,      // Platform observed this from user behavior
    LEARNING_ENGINE,      // Generated by mastery/FSRS engine
    ECONOMIC_ENGINE,      // Generated by service/job completion
    OPENCLAW_WIKI,        // Synced from OpenClaw Memory-Wiki
    EXTERNAL_IMPORT,      // Imported from Obsidian/files/API
    AI_INFERRED,          // AI derived this (lower trust)
    CONSOLIDATION,        // Generated during memory consolidation ("dreaming")
}

// ─── Memory Entry (atomic unit) ───

@Serializable
data class MemoryEntry(
    val id: String,
    val namespace: String,
    val memoryClass: MemoryClass,
    val key: String,
    val value: String,
    val confidence: MemoryConfidence = MemoryConfidence.MODERATE,
    val provenance: MemoryProvenance = MemoryProvenance.USER_EXPLICIT,
    val evidenceRefs: List<String> = emptyList(),
    val tags: List<String> = emptyList(),
    val createdAtEpochMs: Long = System.currentTimeMillis(),
    val updatedAtEpochMs: Long = System.currentTimeMillis(),
    val expiresAtEpochMs: Long? = null,
    val supersededById: String? = null,
    val version: Int = 1,
) {
    val isActive: Boolean
        get() = supersededById == null &&
            (expiresAtEpochMs == null || expiresAtEpochMs > System.currentTimeMillis())

    val isFresh: Boolean
        get() {
            val ageMs = System.currentTimeMillis() - updatedAtEpochMs
            val oneYearMs = 365L * 24 * 60 * 60 * 1000
            return ageMs < oneYearMs
        }
}

// ─── Memory Namespace (privacy wall) ───

/**
 * Namespaces enforce §53 education×economy privacy wall:
 * childhood learning weakness must NEVER become adult employability penalty.
 */
@Serializable
data class MemoryNamespace(
    val id: String,
    val ownerId: String,
    val label: String,
    val accessPolicy: NamespaceAccessPolicy = NamespaceAccessPolicy.PRIVATE,
    val isolatedFromNamespaces: List<String> = emptyList(),
)

enum class NamespaceAccessPolicy {
    PRIVATE,              // Only owner can access
    GUARDIAN_VISIBLE,     // Guardian can see (minor protection)
    SHARED_TEAM,          // Team/organization visible
    PUBLIC_PORTFOLIO,     // Public professional portfolio
}

// ─── Memory Contradiction (OpenClaw contradiction detection) ───

@Serializable
data class MemoryContradiction(
    val id: String,
    val existingEntryId: String,
    val newEntryId: String,
    val detectedAtEpochMs: Long = System.currentTimeMillis(),
    val resolution: ContradictionResolution = ContradictionResolution.PENDING,
    val resolvedByUserId: String? = null,
)

enum class ContradictionResolution {
    PENDING,
    NEWER_WINS,
    OLDER_WINS,
    USER_RESOLVED,
    BOTH_VALID_DIFFERENT_CONTEXT,
}

// ─── Memory Query ───

data class MemoryQuery(
    val ownerId: String,
    val namespace: String? = null,
    val memoryClass: MemoryClass? = null,
    val keyContains: String? = null,
    val semanticQuery: String? = null,
    val minConfidence: MemoryConfidence = MemoryConfidence.LOW,
    val onlyActive: Boolean = true,
    val limit: Int = 20,
)

// ─── Memory Consolidation (OpenClaw "Dreaming") ───

@Serializable
data class MemoryConsolidationEvent(
    val id: String,
    val namespace: String,
    val entriesProcessed: Int,
    val contradictionsFound: Int,
    val entriesSuperseded: Int,
    val newInsightsGenerated: Int,
    val startedAtEpochMs: Long,
    val completedAtEpochMs: Long,
)

// ─── Memory Provider Interface (§69 model independence) ───

/**
 * Abstract interface for memory storage. Implementations:
 * - LocalSqliteMemoryProvider (offline-first, Room)
 * - OpenClawMemoryProvider (OpenClaw Memory-Wiki gateway)
 * - SupabaseMemoryProvider (cloud sync)
 *
 * Changing the provider MUST NOT erase accumulated memory (§69).
 */
interface MemoryProvider {
    val providerId: String

    suspend fun store(entry: MemoryEntry): MemoryEntry
    suspend fun retrieve(id: String): MemoryEntry?
    suspend fun query(query: MemoryQuery): List<MemoryEntry>
    suspend fun supersede(existingId: String, newEntry: MemoryEntry): MemoryEntry
    suspend fun delete(id: String): Boolean
    suspend fun export(namespace: String): List<MemoryEntry>
    suspend fun importEntries(entries: List<MemoryEntry>): Int
    suspend fun detectContradictions(namespace: String): List<MemoryContradiction>
    suspend fun consolidate(namespace: String): MemoryConsolidationEvent
}

// ─── OpenClaw Configuration ───

/**
 * Configuration for connecting to an OpenClaw instance's Memory-Wiki.
 * Uses the Gateway Protocol (WebSocket + RPC) as recommended by OpenClaw docs.
 */
@Serializable
data class OpenClawConfig(
    // This is an intentional loopback-only peer gateway, not a cloud backend.
    // Build it at runtime so physical/release artifacts cannot confuse it with
    // a packaged development backend URL.
    val gatewayUrl: String = buildString {
        append("ws://")
        append("localhost")
        append(':')
        append(3_000)
        append("/ws")
    },
    val apiToken: String = "",
    val wikiVaultId: String = "elysium-memory",
    val syncIntervalMinutes: Int = 15,
    val enableDreaming: Boolean = true,
    val enableContradictionDetection: Boolean = true,
)

/**
 * OpenClaw Memory-Wiki provider stub.
 * Full implementation requires OpenClaw Gateway SDK dependency.
 * This defines the contract and can be tested with mock implementations.
 */
class OpenClawMemoryProvider(
    private val config: OpenClawConfig,
) : MemoryProvider {

    override val providerId: String = "openclaw-wiki-${config.wikiVaultId}"

    override suspend fun store(entry: MemoryEntry): MemoryEntry {
        // TODO: Connect via Gateway WebSocket → wiki_apply RPC
        // Maps MemoryEntry → OpenClaw wiki claim format
        return entry
    }

    override suspend fun retrieve(id: String): MemoryEntry? {
        // TODO: wiki_get RPC
        return null
    }

    override suspend fun query(query: MemoryQuery): List<MemoryEntry> {
        // TODO: wiki_search RPC with hybrid (vector + keyword)
        return emptyList()
    }

    override suspend fun supersede(existingId: String, newEntry: MemoryEntry): MemoryEntry {
        // TODO: wiki_apply with supersession metadata
        return newEntry.copy(version = newEntry.version + 1)
    }

    override suspend fun delete(id: String): Boolean {
        // TODO: wiki_apply delete
        return true
    }

    override suspend fun export(namespace: String): List<MemoryEntry> {
        // TODO: wiki_status + full dump
        return emptyList()
    }

    override suspend fun importEntries(entries: List<MemoryEntry>): Int {
        // TODO: Batch wiki_apply
        return entries.size
    }

    override suspend fun detectContradictions(namespace: String): List<MemoryContradiction> {
        // TODO: wiki_lint RPC
        return emptyList()
    }

    override suspend fun consolidate(namespace: String): MemoryConsolidationEvent {
        // TODO: Trigger OpenClaw "Dreaming" consolidation
        return MemoryConsolidationEvent(
            id = "consolidation-${System.currentTimeMillis()}",
            namespace = namespace,
            entriesProcessed = 0,
            contradictionsFound = 0,
            entriesSuperseded = 0,
            newInsightsGenerated = 0,
            startedAtEpochMs = System.currentTimeMillis(),
            completedAtEpochMs = System.currentTimeMillis(),
        )
    }
}
