// Generated by tools/engine-asset-generator/generate-extended-vehicle-systems.mjs. Do not edit manually.
package com.elysium369.meet.visual3d.domain

object GenericExtendedVehicleSystemsContract {
    val lighting = asset(
        id = "lighting",
        supportedSystemIds = setOf("lighting"),
        bindings = listOf(
            binding("matrix_led_module", 4, -1.67f, 0.67f, -0.80f, GenericSystemSourceAlias("lighting", "Módulo Matrix LED")),
            binding("brake_lamps", 4, -0.56f, 1.37f, 0.98f, GenericSystemSourceAlias("lighting", "Luz de freno"), GenericSystemSourceAlias("lighting", "Tercera luz de freno")),
            binding("headlamp_level_sensor", 5, 0.56f, 0.67f, -1.16f, GenericSystemSourceAlias("lighting", "Sensor de altura para faros")),
            binding("afs_module", 3, 1.67f, 1.37f, 0.80f, GenericSystemSourceAlias("lighting", "Módulo AFS")),
            binding("headlamp_harness", 2, -1.67f, -0.35f, -0.98f, GenericSystemSourceAlias("lighting", "Arnés de faros")),
            binding("bulb_connectors", 5, -0.56f, 0.35f, 1.16f, GenericSystemSourceAlias("lighting", "Conectores de bombillo")),
            binding("rear_lamps", 4, 0.56f, -0.35f, -0.80f, GenericSystemSourceAlias("lighting", "Lámparas traseras")),
            binding("lamp_seals", 6, 1.67f, 0.35f, 0.98f, GenericSystemSourceAlias("lighting", "Sellos de lámparas")),
            binding("door_lamps", 4, -1.67f, -1.37f, -1.16f, GenericSystemSourceAlias("lighting", "Luz de puertas")),
            binding("interior_light_module", 3, -0.56f, -0.67f, 0.80f, GenericSystemSourceAlias("lighting", "Módulo de iluminación interior"))
        )
    )

    val hvac = asset(
        id = "hvac",
        supportedSystemIds = setOf("hvac"),
        bindings = listOf(
            binding("ac_compressor", 2, -2.23f, 1.18f, -0.80f, GenericSystemSourceAlias("hvac", "Compresor A/C")),
            binding("compressor_clutch", 4, -1.12f, 1.88f, 0.98f, GenericSystemSourceAlias("hvac", "Clutch del compresor")),
            binding("compressor_pulley", 4, 0.0f, 1.18f, -1.16f, GenericSystemSourceAlias("hvac", "Polea del compresor")),
            binding("compressor_control_valve", 5, 1.12f, 1.88f, 0.80f, GenericSystemSourceAlias("hvac", "Válvula de control del compresor")),
            binding("expansion_valve", 5, 2.23f, 1.18f, -0.98f, GenericSystemSourceAlias("hvac", "Válvula de expansión")),
            binding("receiver_drier", 3, -2.23f, 0.86f, 1.16f, GenericSystemSourceAlias("hvac", "Filtro deshidratador")),
            binding("refrigerant_lines", 2, -1.12f, 0.16f, -0.80f, GenericSystemSourceAlias("hvac", "Líneas de alta presión"), GenericSystemSourceAlias("hvac", "Líneas de baja presión")),
            binding("ac_pressure_sensor", 5, 0.0f, 0.86f, 0.98f, GenericSystemSourceAlias("hvac", "Sensor de presión A/C")),
            binding("heater_core", 3, 1.12f, 0.16f, -1.16f, GenericSystemSourceAlias("hvac", "Radiador de calefacción")),
            binding("heater_hoses", 2, 2.23f, 0.86f, 0.80f, GenericSystemSourceAlias("hvac", "Mangueras de calefacción")),
            binding("hvac_box", 1, -2.23f, -0.86f, -0.98f, GenericSystemSourceAlias("hvac", "Caja HVAC")),
            binding("blower_motor", 4, -1.12f, -0.16f, 1.16f, GenericSystemSourceAlias("hvac", "Motor blower")),
            binding("blower_pwm", 5, 0.0f, -0.86f, -0.80f, GenericSystemSourceAlias("hvac", "Módulo PWM blower")),
            binding("cabin_filter", 6, 1.12f, -0.16f, 0.98f, GenericSystemSourceAlias("hvac", "Filtro de cabina")),
            binding("air_doors", 5, 2.23f, -0.86f, -1.16f, GenericSystemSourceAlias("hvac", "Actuador blend door"), GenericSystemSourceAlias("hvac", "Actuador mode door"), GenericSystemSourceAlias("hvac", "Actuador recirculation door"), GenericSystemSourceAlias("hvac", "Compuertas internas")),
            binding("air_ducts", 2, -2.23f, -1.18f, 0.80f, GenericSystemSourceAlias("hvac", "Ductos de aire"))
        )
    )

    val passiveSafety = asset(
        id = "passive_safety",
        supportedSystemIds = setOf("passive_safety"),
        bindings = listOf(
            binding("driver_airbag", 6, -1.67f, 0.67f, -0.80f, GenericSystemSourceAlias("passive_safety", "Brazos limpiaparabrisas Airbag conductor")),
            binding("passenger_airbag", 6, -0.56f, 1.37f, 0.98f, GenericSystemSourceAlias("passive_safety", "Airbag pasajero")),
            binding("side_airbags", 6, 0.56f, 0.67f, -1.16f, GenericSystemSourceAlias("passive_safety", "Airbags laterales")),
            binding("curtain_airbags", 6, 1.67f, 1.37f, 0.80f, GenericSystemSourceAlias("passive_safety", "Airbags de cortina")),
            binding("knee_airbag", 6, -1.67f, -0.35f, -0.98f, GenericSystemSourceAlias("passive_safety", "Airbag de rodilla")),
            binding("srs_module", 3, -0.56f, 0.35f, 1.16f, GenericSystemSourceAlias("passive_safety", "Módulo SRS")),
            binding("impact_sensors", 4, 0.56f, -0.35f, -0.80f, GenericSystemSourceAlias("passive_safety", "Sensor impacto frontal"), GenericSystemSourceAlias("passive_safety", "Sensor impacto lateral")),
            binding("safing_sensor", 4, 1.67f, 0.35f, 0.98f, GenericSystemSourceAlias("passive_safety", "Sensor safing")),
            binding("srs_harness", 2, -1.67f, -1.37f, -1.16f, GenericSystemSourceAlias("passive_safety", "Arnés amarillo SRS")),
            binding("srs_connectors", 5, -0.56f, -0.67f, 0.80f, GenericSystemSourceAlias("passive_safety", "Conectores SRS")),
            binding("seatbelt_pretensioner", 5, 0.56f, -1.37f, -0.98f, GenericSystemSourceAlias("passive_safety", "Pretensor cinturón delantero"))
        )
    )

    val adas = asset(
        id = "adas",
        supportedSystemIds = setOf("adas"),
        bindings = listOf(
            binding("reverse_camera", 4, -1.67f, 0.67f, -0.80f, GenericSystemSourceAlias("adas", "Cámara de reversa")),
            binding("front_adas_camera", 4, -0.56f, 1.37f, 0.98f, GenericSystemSourceAlias("adas", "Cámara frontal ADAS")),
            binding("surround_cameras", 4, 0.56f, 0.67f, -1.16f, GenericSystemSourceAlias("adas", "Cámara 360 delantera"), GenericSystemSourceAlias("adas", "Cámara 360 trasera"), GenericSystemSourceAlias("adas", "Cámaras laterales")),
            binding("parking_sensors", 5, 1.67f, 1.37f, 0.80f, GenericSystemSourceAlias("adas", "Sensor parking delantero"), GenericSystemSourceAlias("adas", "Sensor parking trasero")),
            binding("parking_module", 3, -1.67f, -0.35f, -0.98f, GenericSystemSourceAlias("adas", "Módulo parking assist")),
            binding("lane_keep_module", 3, -0.56f, 0.35f, 1.16f, GenericSystemSourceAlias("adas", "Módulo lane keep assist")),
            binding("adaptive_cruise_module", 3, 0.56f, -0.35f, -0.80f, GenericSystemSourceAlias("adas", "Módulo adaptive cruise")),
            binding("aeb_module", 3, 1.67f, 0.35f, 0.98f, GenericSystemSourceAlias("adas", "Módulo AEB")),
            binding("blind_spot_module", 4, -1.67f, -1.37f, -1.16f, GenericSystemSourceAlias("adas", "Módulo blind spot")),
            binding("front_radar", 4, -0.56f, -0.67f, 0.80f),
            binding("ultrasonic_array", 5, 0.56f, -1.37f, -0.98f, GenericSystemSourceAlias("adas", "Sensores ultrasónicos"))
        )
    )

    val body = asset(
        id = "body",
        supportedSystemIds = setOf("body"),
        bindings = listOf(
            binding("front_doors", 2, -2.23f, 0.67f, -0.80f, GenericSystemSourceAlias("body", "Puerta delantera izquierda"), GenericSystemSourceAlias("body", "Puerta delantera derecha")),
            binding("rear_doors", 2, -1.12f, 1.37f, 0.98f, GenericSystemSourceAlias("body", "Puerta trasera izquierda"), GenericSystemSourceAlias("body", "Puerta trasera derecha")),
            binding("tailgate", 2, 0.0f, 0.67f, -1.16f, GenericSystemSourceAlias("body", "Compuerta trasera")),
            binding("side_panels", 1, 1.12f, 1.37f, 0.80f, GenericSystemSourceAlias("body", "Paneles laterales")),
            binding("rocker_panels", 1, 2.23f, 0.67f, -0.98f, GenericSystemSourceAlias("body", "Rocker panels")),
            binding("engine_splash_shields", 3, -2.23f, 0.35f, 1.16f, GenericSystemSourceAlias("body", "Guardapolvos de motor")),
            binding("door_checks", 5, -1.12f, -0.35f, -0.80f, GenericSystemSourceAlias("body", "Limitador de puerta")),
            binding("door_latches", 5, 0.0f, 0.35f, 0.98f, GenericSystemSourceAlias("body", "Cerradura de puerta")),
            binding("exterior_handles", 5, 1.12f, -0.35f, -1.16f, GenericSystemSourceAlias("body", "Manija exterior")),
            binding("window_motors", 4, 2.23f, 0.35f, 0.80f, GenericSystemSourceAlias("body", "Motor de ventana")),
            binding("door_glass", 3, -2.23f, -1.37f, -0.98f, GenericSystemSourceAlias("body", "Vidrio de puerta")),
            binding("rear_glass", 3, -1.12f, -0.67f, 1.16f, GenericSystemSourceAlias("body", "Vidrio trasero")),
            binding("side_mirrors", 3, 0.0f, -1.37f, -0.80f, GenericSystemSourceAlias("body", "Espejo lateral izquierdo"), GenericSystemSourceAlias("body", "Espejo lateral derecho")),
            binding("mirror_motors", 5, 1.12f, -0.67f, 0.98f, GenericSystemSourceAlias("body", "Motor ajuste espejo"), GenericSystemSourceAlias("body", "Motor plegado espejo")),
            binding("mirror_heaters", 5, 2.23f, -1.37f, -1.16f, GenericSystemSourceAlias("body", "Calefactor espejo"))
        )
    )

    val wipers = asset(
        id = "wipers",
        supportedSystemIds = setOf("wipers"),
        bindings = listOf(
            binding("front_wiper_motor", 3, -1.67f, 0.67f, -0.80f, GenericSystemSourceAlias("wipers", "Motor limpiaparabrisas delantero")),
            binding("wiper_linkage", 4, -0.56f, 1.37f, 0.98f, GenericSystemSourceAlias("wipers", "Varillaje limpiaparabrisas")),
            binding("rear_wiper_motor", 3, 0.56f, 0.67f, -1.16f, GenericSystemSourceAlias("wipers", "Motor limpiaparabrisas trasero")),
            binding("rear_wiper_arm", 5, 1.67f, 1.37f, 0.80f, GenericSystemSourceAlias("wipers", "Brazo trasero")),
            binding("washer_reservoir", 1, -1.67f, -0.35f, -0.98f, GenericSystemSourceAlias("wipers", "Depósito lavaparabrisas")),
            binding("washer_pumps", 4, -0.56f, 0.35f, 1.16f, GenericSystemSourceAlias("wipers", "Bomba lavaparabrisas delantera"), GenericSystemSourceAlias("wipers", "Bomba lavaparabrisas trasera")),
            binding("washer_hoses", 2, 0.56f, -0.35f, -0.80f, GenericSystemSourceAlias("wipers", "Mangueras lavaparabrisas")),
            binding("washer_level_sensor", 5, 1.67f, 0.35f, 0.98f, GenericSystemSourceAlias("wipers", "Sensor nivel líquido limpiaparabrisas")),
            binding("wiper_relay", 3, -1.67f, -1.37f, -1.16f, GenericSystemSourceAlias("wipers", "Relé wiper")),
            binding("multifunction_switch", 4, -0.56f, -0.67f, 0.80f, GenericSystemSourceAlias("wipers", "Switch multifunción")),
            binding("rain_sensor", 5, 0.56f, -1.37f, -0.98f, GenericSystemSourceAlias("wipers", "Sensor lluvia"))
        )
    )

    val interior = asset(
        id = "interior",
        supportedSystemIds = setOf("interior"),
        bindings = listOf(
            binding("hvac_panel", 3, -2.23f, 0.67f, -0.80f, GenericSystemSourceAlias("interior", "Panel HVAC")),
            binding("armrest", 2, -1.12f, 1.37f, 0.98f, GenericSystemSourceAlias("interior", "Apoyabrazos")),
            binding("hazard_switch", 5, 0.0f, 0.67f, -1.16f, GenericSystemSourceAlias("interior", "Switch hazard")),
            binding("defog_switch", 5, 1.12f, 1.37f, 0.80f, GenericSystemSourceAlias("interior", "Switch desempañador")),
            binding("light_switch", 5, 2.23f, 0.67f, -0.98f, GenericSystemSourceAlias("interior", "Switch luces")),
            binding("parking_brake", 4, -2.23f, 0.35f, 1.16f, GenericSystemSourceAlias("interior", "Freno de mano")),
            binding("front_seats", 2, -1.12f, -0.35f, -0.80f, GenericSystemSourceAlias("interior", "Asiento conductor"), GenericSystemSourceAlias("interior", "Asiento pasajero")),
            binding("rear_seats", 2, 0.0f, 0.35f, 0.98f, GenericSystemSourceAlias("interior", "Asientos traseros")),
            binding("seat_rails", 4, 1.12f, -0.35f, -1.16f, GenericSystemSourceAlias("interior", "Rieles de asiento")),
            binding("seat_motors", 5, 2.23f, 0.35f, 0.80f, GenericSystemSourceAlias("interior", "Motor ajuste longitudinal"), GenericSystemSourceAlias("interior", "Motor ajuste altura"), GenericSystemSourceAlias("interior", "Motor ajuste respaldo"), GenericSystemSourceAlias("interior", "Motor lumbar")),
            binding("seat_memory", 5, -2.23f, -1.37f, -0.98f, GenericSystemSourceAlias("interior", "Módulo memoria")),
            binding("occupant_sensor", 5, -1.12f, -0.67f, 1.16f, GenericSystemSourceAlias("interior", "Sensor ocupante")),
            binding("door_trims", 3, 0.0f, -1.37f, -0.80f, GenericSystemSourceAlias("interior", "Paneles de puerta"), GenericSystemSourceAlias("interior", "Manijas interiores"), GenericSystemSourceAlias("interior", "Espejos de parasol"))
        )
    )

    val infotainment = asset(
        id = "infotainment",
        supportedSystemIds = setOf("infotainment"),
        bindings = listOf(
            binding("bluetooth_module", 3, -1.67f, 0.16f, -0.80f, GenericSystemSourceAlias("infotainment", "Módulo Bluetooth")),
            binding("wifi_module", 3, -0.56f, 0.86f, 0.98f, GenericSystemSourceAlias("infotainment", "Módulo WiFi")),
            binding("cellular_module", 3, 0.56f, 0.16f, -1.16f, GenericSystemSourceAlias("infotainment", "Módulo celular")),
            binding("steering_controls", 4, 1.67f, 0.86f, 0.80f, GenericSystemSourceAlias("infotainment", "Mandos al volante")),
            binding("phone_projection_module", 3, -1.67f, -0.86f, -0.98f, GenericSystemSourceAlias("infotainment", "Módulo CarPlay/Android Auto")),
            binding("oem_dashcam", 4, -0.56f, -0.16f, 1.16f, GenericSystemSourceAlias("infotainment", "Cámara dashcam OEM")),
            binding("antenna_network", 4, 0.56f, -0.86f, -0.80f),
            binding("audio_bus", 2, 1.67f, -0.16f, 0.98f)
        )
    )

    val access = asset(
        id = "access",
        supportedSystemIds = setOf("access"),
        bindings = listOf(
            binding("ignition_switch", 4, -1.67f, 0.67f, -0.80f, GenericSystemSourceAlias("access", "Switch de ignición")),
            binding("immobilizer_module", 3, -0.56f, 1.37f, 0.98f, GenericSystemSourceAlias("access", "Módulo inmovilizador")),
            binding("central_lock_actuators", 5, 0.56f, 0.67f, -1.16f, GenericSystemSourceAlias("access", "Actuadores cierre central")),
            binding("trunk_actuator", 5, 1.67f, 1.37f, 0.80f, GenericSystemSourceAlias("access", "Actuador baúl")),
            binding("hood_sensor", 5, -1.67f, -0.35f, -0.98f, GenericSystemSourceAlias("access", "Sensor capó")),
            binding("trunk_sensor", 5, -0.56f, 0.35f, 1.16f, GenericSystemSourceAlias("access", "Sensor baúl")),
            binding("ultrasonic_security_sensor", 5, 0.56f, -0.35f, -0.80f, GenericSystemSourceAlias("access", "Sensor ultrasonido")),
            binding("tilt_sensor", 5, 1.67f, 0.35f, 0.98f, GenericSystemSourceAlias("access", "Sensor inclinación")),
            binding("motion_sensor", 5, -1.67f, -1.37f, -1.16f, GenericSystemSourceAlias("access", "Sensor movimiento"))
        )
    )

    val hybridEv = asset(
        id = "hybrid_ev",
        supportedSystemIds = setOf("hybrid_ev"),
        bindings = listOf(
            binding("hv_battery", 1, -2.23f, 1.18f, -0.80f, GenericSystemSourceAlias("hybrid_ev", "Batería HV")),
            binding("battery_modules", 3, -1.12f, 1.88f, 0.98f, GenericSystemSourceAlias("hybrid_ev", "Módulos de batería")),
            binding("hv_fuse", 5, 0.0f, 1.18f, -1.16f, GenericSystemSourceAlias("hybrid_ev", "Fusible HV")),
            binding("cell_voltage_sensors", 5, 1.12f, 1.88f, 0.80f, GenericSystemSourceAlias("hybrid_ev", "Sensores de voltaje por celda")),
            binding("battery_temperature_sensors", 5, 2.23f, 1.18f, -0.98f, GenericSystemSourceAlias("hybrid_ev", "Sensores de temperatura batería")),
            binding("current_sensors", 5, -2.23f, 0.86f, 1.16f, GenericSystemSourceAlias("hybrid_ev", "Sensores de corriente")),
            binding("hv_junction_box", 3, -1.12f, 0.16f, -0.80f, GenericSystemSourceAlias("hybrid_ev", "Caja de unión HV")),
            binding("orange_hv_cables", 2, 0.0f, 0.86f, 0.98f, GenericSystemSourceAlias("hybrid_ev", "Cables naranja HV")),
            binding("hv_connectors", 5, 1.12f, 0.16f, -1.16f, GenericSystemSourceAlias("hybrid_ev", "Conectores HV")),
            binding("charge_port", 4, 2.23f, 0.86f, 0.80f, GenericSystemSourceAlias("hybrid_ev", "Tapa puerto carga")),
            binding("front_traction_motor", 2, -2.23f, -0.86f, -0.98f, GenericSystemSourceAlias("hybrid_ev", "Motor eléctrico delantero")),
            binding("rear_traction_motor", 2, -1.12f, -0.16f, 1.16f, GenericSystemSourceAlias("hybrid_ev", "Motor eléctrico trasero")),
            binding("rotor_position_sensor", 5, 0.0f, -0.86f, -0.80f, GenericSystemSourceAlias("hybrid_ev", "Sensor posición rotor")),
            binding("reduction_gear", 4, 1.12f, -0.16f, 0.98f, GenericSystemSourceAlias("hybrid_ev", "Reductor")),
            binding("traction_inverters", 3, 2.23f, -0.86f, -1.16f, GenericSystemSourceAlias("hybrid_ev", "Inverter motor delantero"), GenericSystemSourceAlias("hybrid_ev", "Inverter motor trasero")),
            binding("e_axle", 3, -2.23f, -1.18f, 0.80f, GenericSystemSourceAlias("hybrid_ev", "Unidad e-axle")),
            binding("hybrid_control_module", 3, -1.12f, -1.88f, -0.98f, GenericSystemSourceAlias("hybrid_ev", "Módulo control híbrido")),
            binding("regenerative_brake", 4, 0.0f, -1.18f, 1.16f, GenericSystemSourceAlias("hybrid_ev", "Freno regenerativo"))
        )
    )

    val fluids = asset(
        id = "fluids",
        supportedSystemIds = setOf("fluids"),
        bindings = listOf(
            binding("engine_oil", 2, -2.23f, 0.67f, -0.80f, GenericSystemSourceAlias("fluids", "Aceite de motor")),
            binding("brake_fluid", 2, -1.12f, 1.37f, 0.98f, GenericSystemSourceAlias("fluids", "Líquido de frenos")),
            binding("ac_oil", 2, 0.0f, 0.67f, -1.16f, GenericSystemSourceAlias("fluids", "Aceite compresor A/C")),
            binding("bearing_grease", 2, 1.12f, 1.37f, 0.80f, GenericSystemSourceAlias("fluids", "Grasa rodamientos")),
            binding("oil_filter", 4, 2.23f, 0.67f, -0.98f, GenericSystemSourceAlias("fluids", "Filtro aceite")),
            binding("air_filter", 4, -2.23f, 0.35f, 1.16f, GenericSystemSourceAlias("fluids", "Filtro aire")),
            binding("fuel_filter", 4, -1.12f, -0.35f, -0.80f, GenericSystemSourceAlias("fluids", "Filtro combustible")),
            binding("cabin_filter", 4, 0.0f, 0.35f, 0.98f, GenericSystemSourceAlias("fluids", "Filtro cabina")),
            binding("transmission_filter", 4, 1.12f, -0.35f, -1.16f, GenericSystemSourceAlias("fluids", "Filtro transmisión")),
            binding("brake_pads", 5, 2.23f, 0.35f, 0.80f, GenericSystemSourceAlias("fluids", "Pastillas freno")),
            binding("brake_shoes", 5, -2.23f, -1.37f, -0.98f, GenericSystemSourceAlias("fluids", "Zapatas freno")),
            binding("brake_discs", 5, -1.12f, -0.67f, 1.16f, GenericSystemSourceAlias("fluids", "Discos freno"))
        )
    )

    val hardware = asset(
        id = "hardware",
        supportedSystemIds = setOf("hardware"),
        bindings = listOf(
            binding("head_bolts", 6, -2.23f, 0.67f, -0.80f, GenericSystemSourceAlias("hardware", "Pernos de culata torque-to-yield")),
            binding("rod_bolts", 6, -1.12f, 1.37f, 0.98f, GenericSystemSourceAlias("hardware", "Pernos de biela")),
            binding("flywheel_bolts", 6, 0.0f, 0.67f, -1.16f, GenericSystemSourceAlias("hardware", "Pernos de volante")),
            binding("converter_bolts", 6, 1.12f, 1.37f, 0.80f, GenericSystemSourceAlias("hardware", "Pernos de convertidor")),
            binding("caliper_bolts", 6, 2.23f, 0.67f, -0.98f, GenericSystemSourceAlias("hardware", "Pernos de caliper")),
            binding("engine_mount_bolts", 6, -2.23f, 0.35f, 1.16f, GenericSystemSourceAlias("hardware", "Pernos de soporte motor")),
            binding("alignment_bolts", 6, -1.12f, -0.35f, -0.80f, GenericSystemSourceAlias("hardware", "Pernos excéntricos alineación")),
            binding("axle_nuts", 6, 0.0f, 0.35f, 0.98f, GenericSystemSourceAlias("hardware", "Tuercas de eje")),
            binding("flat_gaskets", 5, 1.12f, -0.35f, -1.16f, GenericSystemSourceAlias("hardware", "Juntas planas")),
            binding("mls_gaskets", 5, 2.23f, 0.35f, 0.80f, GenericSystemSourceAlias("hardware", "Juntas metálicas MLS")),
            binding("bushings", 5, -2.23f, -1.37f, -0.98f, GenericSystemSourceAlias("hardware", "Bujes")),
            binding("metal_clamps", 5, -1.12f, -0.67f, 1.16f, GenericSystemSourceAlias("hardware", "Abrazaderas metálicas"))
        )
    )

    val functionalOverview = asset(
        id = "functional_overview",
        supportedSystemIds = setOf("overview"),
        bindings = listOf(
            binding("sensor_domain", 1, -2.23f, 0.67f, -0.80f, GenericSystemSourceAlias("overview", "│    ├── Sensors")),
            binding("engine_grounds", 2, -1.12f, 1.37f, 0.98f, GenericSystemSourceAlias("overview", "Tierras del motor")),
            binding("main_fusible_link", 2, 0.0f, 0.67f, -1.16f, GenericSystemSourceAlias("overview", "Fusible link principal")),
            binding("battery_ibs", 3, 1.12f, 1.37f, 0.80f, GenericSystemSourceAlias("overview", "Sensor IBS de batería")),
            binding("main_relay", 3, 2.23f, 0.67f, -0.98f, GenericSystemSourceAlias("overview", "Relé principal")),
            binding("prndl_sensor", 3, -2.23f, 0.35f, 1.16f, GenericSystemSourceAlias("overview", "Sensor de rango PRNDL")),
            binding("neutral_safety_switch", 3, -1.12f, -0.35f, -0.80f, GenericSystemSourceAlias("overview", "Neutral safety switch")),
            binding("transmission_solenoids", 4, 0.0f, 0.35f, 0.98f, GenericSystemSourceAlias("overview", "Solenoides internos de transmisión")),
            binding("transmission_harness", 4, 1.12f, -0.35f, -1.16f, GenericSystemSourceAlias("overview", "Arnés interno de transmisión")),
            binding("transmission_bulkhead", 4, 2.23f, 0.35f, 0.80f, GenericSystemSourceAlias("overview", "Conector pasamuros de transmisión")),
            binding("evap_pressure_sensor", 5, -2.23f, -1.37f, -0.98f, GenericSystemSourceAlias("overview", "Sensor de presión EVAP")),
            binding("evap_valves", 5, -1.12f, -0.67f, 1.16f, GenericSystemSourceAlias("overview", "Válvula vent EVAP"), GenericSystemSourceAlias("overview", "Válvula purge EVAP"))
        )
    )

    val assets: List<GenericSystemAssetDefinition> = listOf(
        lighting,
        hvac,
        passiveSafety,
        adas,
        body,
        wipers,
        interior,
        infotainment,
        access,
        hybridEv,
        fluids,
        hardware,
        functionalOverview
    )

    private fun asset(
        id: String,
        supportedSystemIds: Set<String>,
        bindings: List<GenericSystemAssetBinding>
    ) = GenericSystemAssetDefinition(
        id = id,
        assetPath = "models/vehicle_systems/$id/generic_$id.glb",
        manifestPath = "models/vehicle_systems/$id/manifest.json",
        supportedSystemIds = supportedSystemIds,
        bindings = bindings
    )

    private fun binding(
        meshKey: String,
        serviceStage: Int,
        offsetX: Float,
        offsetY: Float,
        offsetZ: Float,
        vararg aliases: GenericSystemSourceAlias
    ) = GenericSystemAssetBinding(
        meshKey = meshKey,
        sourceAliases = aliases.toSet(),
        serviceStage = serviceStage,
        explodedOffset = CatalogServiceOffset(offsetX, offsetY, offsetZ)
    )
}
