package com.elysium369.meet.core.monetization

enum class FeatureKey {
    SCAN_BASIC,
    SCAN_ADVANCED,
    DTC_BASIC,
    DTC_EXPERT,
    REPORT_PDF_BASIC,
    REPORT_PDF_CERTIFIED,
    LIVELINK_30_MIN,
    LIVELINK_PRO,
    AI_DIAGNOSTIC_ADVANCED,
    GAUGE_BUILDER_ADVANCED,
    GAUGE_MARKET_BUY,
    GAUGE_MARKET_SELL,
    OSCILLOSCOPE_USB,
    SERVICE_RESET,
    ACTIVE_TEST,
    FLEET_DVIR,
    FLEET_DASHBOARD,
    MANUAL_RAG_OFFLINE
}
