import { DtcEntry } from './obd2-database';

export const OBD2_DATABASE_P5: Record<string, DtcEntry> = {
  // === Específicos Toyota/Lexus ===
  'P0031': { title: 'Calentador Sensor O2 - Bajo (B1S1)', desc: 'Circuito bajo del calentador del sensor O2 upstream banco 1.', fix: 'Verificar cableado del calentador, fusible y reemplazar sensor O2.', severity: 'low' },
  'P0037': { title: 'Calentador Sensor O2 - Bajo (B1S2)', desc: 'Circuito bajo del calentador del sensor O2 downstream banco 1.', fix: 'Verificar cableado y reemplazar sensor O2 downstream.', severity: 'low' },
  'P0138': { title: 'Sensor O2 Alto Voltaje (B1S2)', desc: 'Voltaje alto en el sensor de oxígeno downstream banco 1.', fix: 'Revisar catalizador, sensor O2 downstream y fugas de escape.', severity: 'medium' },
  'P0139': { title: 'Respuesta Lenta del Sensor O2 (B1S2)', desc: 'El sensor O2 downstream tarda demasiado en responder.', fix: 'Reemplazar sensor O2 downstream. Verificar catalizador.', severity: 'medium' },
  'P0156': { title: 'Circuito del Sensor O2 (B2S2)', desc: 'Mal funcionamiento del sensor O2 downstream banco 2.', fix: 'Revisar sensor O2 B2S2, cableado y conector.', severity: 'medium' },
  'P0157': { title: 'Sensor O2 Bajo Voltaje (B2S2)', desc: 'Voltaje bajo en el sensor O2 downstream banco 2.', fix: 'Verificar sensor O2, catalizador banco 2 y fugas de escape.', severity: 'medium' },
  'P0158': { title: 'Sensor O2 Alto Voltaje (B2S2)', desc: 'Voltaje alto en el sensor O2 downstream banco 2.', fix: 'Revisar catalizador banco 2, sensor O2 y sistema de escape.', severity: 'medium' },
  'P0161': { title: 'Circuito del Calentador del Sensor O2 (B2S2)', desc: 'Falla en el calentador del sensor O2 downstream banco 2.', fix: 'Revisar fusible, cableado y sensor O2 B2S2.', severity: 'low' },
  // === Específicos GM/Chevrolet ===
  'P0121': { title: 'Rango/Rendimiento del Sensor TPS', desc: 'El sensor de posición del acelerador muestra valores inconsistentes.', fix: 'Limpiar cuerpo de aceleración, revisar sensor TPS y cableado.', severity: 'medium' },
  'P0327': { title: 'Sensor de Detonación - Entrada Baja (B1)', desc: 'Señal baja del sensor knock banco 1.', fix: 'Verificar torque del sensor, cableado y reemplazar si es necesario.', severity: 'medium' },
  'P0332': { title: 'Sensor de Detonación - Entrada Baja (B2)', desc: 'Señal baja del sensor knock banco 2.', fix: 'Verificar torque del sensor knock banco 2, cableado y arnés.', severity: 'medium' },
  'P0442': { title: 'Fuga Pequeña en Sistema EVAP', desc: 'Fuga pequeña detectada en el sistema de emisiones evaporativas.', fix: 'Verificar tapa de combustible, mangueras y conexiones del sistema EVAP.', severity: 'low' },
  'P0449': { title: 'Circuito de Válvula de Ventilación EVAP', desc: 'Falla en el solenoide de ventilación del canister.', fix: 'Revisar solenoide de ventilación, cableado y conector.', severity: 'low' },
  'P0452': { title: 'Sensor de Presión del Tanque EVAP - Bajo', desc: 'Señal baja del sensor de presión del tanque de combustible.', fix: 'Revisar sensor FTP, cableado y conector.', severity: 'low' },
  'P0453': { title: 'Sensor de Presión del Tanque EVAP - Alto', desc: 'Señal alta del sensor de presión del tanque de combustible.', fix: 'Revisar sensor FTP, posible corto o circuito abierto.', severity: 'low' },
  // === Específicos Ford ===
  'P0316': { title: 'Fallo de Encendido en Arranque (Ford)', desc: 'Se detectaron fallos de encendido durante los primeros 1000 RPM.', fix: 'Revisar bujías, bobinas, inyectores y compresión.', severity: 'high' },
  'P1151': { title: 'Sensor O2 Sin Cambio - Mezcla Pobre (B2, Ford)', desc: 'El sensor O2 banco 2 indica condición pobre constante.', fix: 'Revisar fugas de vacío banco 2, inyectores y presión de combustible.', severity: 'medium' },
  'P1152': { title: 'Sensor O2 Sin Cambio - Mezcla Rica (B2, Ford)', desc: 'El sensor O2 banco 2 indica condición rica constante.', fix: 'Revisar inyectores con fuga banco 2, regulador de presión.', severity: 'medium' },
  'P1233': { title: 'Monitor de Bomba de Combustible Deshabilitado (Ford)', desc: 'El driver de la bomba de combustible fue deshabilitado por la ECU.', fix: 'Revisar módulo FPDM, interruptor inercial de combustible y cableado.', severity: 'high' },
  'P1235': { title: 'Control de Bomba de Combustible Fuera de Rango (Ford)', desc: 'La señal de control de la bomba de combustible está fuera de rango.', fix: 'Revisar bomba de combustible, módulo FPDM y cableado.', severity: 'high' },
  // === Específicos VW/Audi ===
  'P0234': { title: 'Sobrealimentación del Turbo Excesiva', desc: 'El turbo genera más presión de la permitida.', fix: 'Revisar wastegate, solenoide N75, mangueras de vacío y sensor MAP.', severity: 'high' },
  'P0235': { title: 'Circuito del Sensor de Presión del Turbo A', desc: 'Mal funcionamiento del sensor de presión de sobrealimentación.', fix: 'Revisar sensor de presión del turbo, cableado y mangueras.', severity: 'medium' },
  'P0236': { title: 'Rango/Rendimiento del Sensor de Presión del Turbo', desc: 'El sensor de presión del turbo reporta valores inconsistentes.', fix: 'Verificar sensor de boost, líneas de vacío y actuador.', severity: 'medium' },
  'P0237': { title: 'Sensor de Presión del Turbo - Entrada Baja', desc: 'Señal baja del sensor de presión de sobrealimentación.', fix: 'Verificar cableado del sensor de boost, posible corto a tierra.', severity: 'medium' },
  'P0238': { title: 'Sensor de Presión del Turbo - Entrada Alta', desc: 'Señal alta del sensor de presión de sobrealimentación.', fix: 'Verificar cableado, posible cortocircuito o sensor dañado.', severity: 'medium' },
  'P0243': { title: 'Circuito del Solenoide Wastegate A', desc: 'Mal funcionamiento del circuito de control de la wastegate.', fix: 'Revisar solenoide de wastegate (N75 en VW), cableado y actuador.', severity: 'medium' },
  'P0244': { title: 'Rango/Rendimiento del Solenoide Wastegate', desc: 'El actuador de la wastegate no responde correctamente.', fix: 'Verificar solenoide wastegate, actuador y mangueras de vacío.', severity: 'medium' },
  'P0245': { title: 'Solenoide Wastegate A - Bajo', desc: 'Señal baja en el circuito del solenoide de la wastegate.', fix: 'Verificar cableado del solenoide, posible corto a tierra.', severity: 'medium' },
  'P0299': { title: 'Subpresión del Turbo/Supercargador', desc: 'El turbo no genera la presión de sobrealimentación esperada.', fix: 'Revisar fugas en mangueras de intercooler, wastegate y turbo.', severity: 'medium' },
  // === Específicos Honda ===
  'P1077': { title: 'Sensor de Posición de la Válvula de Admisión (Honda)', desc: 'Mal funcionamiento del circuito del actuador de la válvula de admisión.', fix: 'Revisar actuador de admisión, cableado y conector.', severity: 'medium' },
  'P1078': { title: 'Válvula de Admisión Atascada (Honda)', desc: 'La válvula de control de admisión no opera correctamente.', fix: 'Limpiar válvula de admisión, revisar actuador.', severity: 'medium' },
  'P1157': { title: 'Sensor de Relación Aire/Combustible - Bajo (Honda)', desc: 'Señal baja del sensor A/F banco 1.', fix: 'Revisar sensor A/F, cableado y fugas de escape.', severity: 'medium' },
  'P1361': { title: 'Señal Intermitente del Sensor TDC (Honda)', desc: 'El sensor de punto muerto superior genera señal irregular.', fix: 'Revisar sensor TDC, cableado y conector. Limpiar sensor.', severity: 'high' },
  'P1381': { title: 'Señal Intermitente del Sensor CYP (Honda)', desc: 'El sensor de posición del cilindro genera señal intermitente.', fix: 'Revisar sensor CYP, cableado y conector.', severity: 'high' },
  'P1457': { title: 'Fuga en Sistema EVAP (Honda)', desc: 'El sistema de emisiones evaporativas detectó una fuga.', fix: 'Revisar tapa de combustible, canister y mangueras EVAP.', severity: 'low' },
  // === Más códigos U (Red) ===
  'U0001': { title: 'Bus CAN de Alta Velocidad - Sin Comunicación', desc: 'El bus CAN-H no tiene comunicación activa.', fix: 'Verificar cableado CAN-H, resistencias de terminación y todos los módulos.', severity: 'high' },
  'U0002': { title: 'Bus CAN de Alta Velocidad - Rendimiento', desc: 'Errores de comunicación en el bus CAN de alta velocidad.', fix: 'Buscar interferencias EMI, verificar cableado trenzado y conectores.', severity: 'high' },
  'U0003': { title: 'Bus CAN de Alta Velocidad - Abierto', desc: 'Circuito abierto detectado en el bus CAN-H.', fix: 'Verificar continuidad del cableado CAN, buscar corte en arnés.', severity: 'high' },
  'U0004': { title: 'Bus CAN de Alta Velocidad - Bajo', desc: 'La línea CAN-H tiene voltaje bajo permanente.', fix: 'Buscar corto a tierra en CAN-H, desconectar módulos para aislar falla.', severity: 'high' },
  'U0005': { title: 'Bus CAN de Alta Velocidad - Alto', desc: 'La línea CAN-H tiene voltaje alto permanente.', fix: 'Buscar corto a positivo en CAN-H, aislar módulo defectuoso.', severity: 'high' },
  'U0010': { title: 'Bus CAN de Media Velocidad - Sin Comunicación', desc: 'El bus CAN de media velocidad no tiene comunicación.', fix: 'Verificar cableado del bus CAN de media velocidad y módulos conectados.', severity: 'medium' },
  'U0028': { title: 'Bus LIN del Vehículo - Sin Comunicación', desc: 'El bus de comunicación LIN no está operativo.', fix: 'Verificar cableado LIN, módulos esclavos y módulo maestro.', severity: 'medium' },
  'U0107': { title: 'Pérdida de Comunicación con TAC', desc: 'Sin comunicación con el módulo del acelerador electrónico.', fix: 'Revisar cableado CAN al módulo TAC, alimentación y tierras.', severity: 'high' },
  'U0109': { title: 'Pérdida de Comunicación con Calefacción/AC', desc: 'Sin comunicación con el módulo HVAC.', fix: 'Revisar fusibles del HVAC, cableado CAN y módulo de clima.', severity: 'low' },
  'U0126': { title: 'Pérdida de Comunicación con Control de Dirección', desc: 'Sin comunicación con el módulo de dirección eléctrica.', fix: 'Revisar fusibles, cableado CAN y módulo EPS.', severity: 'high' },
  'U0131': { title: 'Pérdida de Comunicación con Sistema de Frenos', desc: 'Sin comunicación con el módulo de frenos de potencia.', fix: 'Revisar fusibles, cableado CAN y módulo de frenos.', severity: 'high' },
  'U0151': { title: 'Pérdida de Comunicación con Sistema de Retención', desc: 'Sin comunicación con el módulo SRS/Airbag.', fix: 'Revisar cableado CAN al módulo SRS, fusibles y conectores.', severity: 'high' },
  'U0164': { title: 'Pérdida de Comunicación con HVAC Trasero', desc: 'Sin comunicación con el módulo de clima trasero.', fix: 'Revisar cableado del módulo HVAC trasero y fusibles.', severity: 'low' },
  'U0199': { title: 'Pérdida de Comunicación con Módulo de Puerta', desc: 'Sin comunicación con el módulo de puerta del conductor.', fix: 'Revisar cableado de la puerta, conector y módulo de puerta.', severity: 'low' },
  'U0293': { title: 'Datos de Información del Vehículo No Recibidos', desc: 'El módulo no recibe datos de configuración del vehículo.', fix: 'Reprogramar módulos con información de VIN correcta.', severity: 'medium' },
  'U0401': { title: 'Datos Inválidos Recibidos del ECM/PCM', desc: 'Un módulo recibe datos corruptos del ECM.', fix: 'Verificar cableado CAN, reprogramar ECM si es necesario.', severity: 'medium' },
  'U0402': { title: 'Datos Inválidos Recibidos del TCM', desc: 'Un módulo recibe datos corruptos de la transmisión.', fix: 'Verificar cableado CAN al TCM, reprogramar si es necesario.', severity: 'medium' },
};
