import { DtcEntry } from './obd2-database';

export const OBD2_DATABASE_P3: Record<string, DtcEntry> = {
  'P0010': { title: 'Circuito del Actuador de Posición del Árbol de Levas A (Banco 1)', desc: 'Mal funcionamiento del solenoide de sincronización variable de válvulas (VVT).', fix: 'Revisar solenoide VVT, nivel/presión de aceite y cableado.', severity: 'medium' },
  'P0011': { title: 'Sincronización del Árbol de Levas A Sobre-Avanzada (Banco 1)', desc: 'El árbol de levas está más avanzado de lo que la ECU comanda.', fix: 'Cambiar aceite, revisar solenoide VVT, cadena de distribución y tensor.', severity: 'medium' },
  'P0012': { title: 'Sincronización del Árbol de Levas A Sobre-Retrasada (Banco 1)', desc: 'El árbol de levas está más retrasado de lo que la ECU comanda.', fix: 'Cambiar aceite, revisar solenoide VVT, cadena de distribución.', severity: 'medium' },
  'P0013': { title: 'Circuito del Actuador de Posición del Árbol de Levas B (Banco 1)', desc: 'Mal funcionamiento del solenoide VVT del escape.', fix: 'Revisar solenoide VVT de escape, nivel de aceite y cableado.', severity: 'medium' },
  'P0014': { title: 'Sincronización del Árbol de Levas B Sobre-Avanzada (Banco 1)', desc: 'Árbol de levas de escape sobre-avanzado.', fix: 'Cambiar aceite, revisar solenoide VVT de escape y cadena de distribución.', severity: 'medium' },
  'P0016': { title: 'Correlación de Posición Cigüeñal/Árbol de Levas (Banco 1)', desc: 'Las posiciones del cigüeñal y árbol de levas no están sincronizadas.', fix: 'Verificar cadena/correa de distribución, tensores y sensores CKP/CMP.', severity: 'high' },
  'P0017': { title: 'Correlación de Posición Cigüeñal/Árbol de Levas B (Banco 1)', desc: 'Desincronización entre cigüeñal y árbol de levas de escape.', fix: 'Verificar cadena de distribución, guías, tensores y sensores.', severity: 'high' },
  'P0020': { title: 'Circuito del Actuador VVT A (Banco 2)', desc: 'Falla en el solenoide de sincronización variable banco 2.', fix: 'Revisar solenoide VVT banco 2, aceite y cableado.', severity: 'medium' },
  'P0021': { title: 'Sincronización del Árbol de Levas A Sobre-Avanzada (Banco 2)', desc: 'Árbol de levas banco 2 sobre-avanzado.', fix: 'Cambiar aceite, revisar solenoide VVT banco 2 y distribución.', severity: 'medium' },
  'P0030': { title: 'Circuito del Calentador del Sensor O2 (B1S1)', desc: 'Falla en el circuito de control del calentador del sensor de oxígeno.', fix: 'Revisar fusible, relé, cableado y sensor O2 B1S1.', severity: 'low' },
  'P0031': { title: 'Calentador Sensor O2 - Bajo (B1S1)', desc: 'Circuito bajo en el calentador del sensor O2 banco 1 sensor 1.', fix: 'Verificar cableado y reemplazar sensor O2 si la resistencia es incorrecta.', severity: 'low' },
  'P0036': { title: 'Circuito del Calentador del Sensor O2 (B1S2)', desc: 'Falla en el calentador del sensor O2 downstream banco 1.', fix: 'Revisar fusible, cableado y sensor O2 B1S2.', severity: 'low' },
  'P0037': { title: 'Calentador Sensor O2 - Bajo (B1S2)', desc: 'Circuito bajo del calentador del sensor O2 downstream banco 1.', fix: 'Verificar cableado y reemplazar sensor O2 downstream.', severity: 'low' },
  'P0050': { title: 'Circuito del Calentador del Sensor O2 (B2S1)', desc: 'Falla en el calentador del sensor O2 banco 2 sensor 1.', fix: 'Revisar fusible, cableado y sensor O2 B2S1.', severity: 'low' },
  'P0056': { title: 'Circuito del Calentador del Sensor O2 (B2S2)', desc: 'Falla en el calentador del sensor O2 downstream banco 2.', fix: 'Revisar fusible, cableado y sensor O2 B2S2.', severity: 'low' },
  'P0068': { title: 'Correlación MAP/MAF - Cuerpo de Aceleración', desc: 'Las lecturas del MAP y MAF no coinciden con la posición del acelerador.', fix: 'Limpiar cuerpo de aceleración, revisar sensores MAP/MAF y fugas de vacío.', severity: 'medium' },
  'P0069': { title: 'Correlación MAP/Presión Barométrica', desc: 'Discrepancia entre presión del múltiple y presión barométrica.', fix: 'Verificar sensor MAP, manguera de vacío y sensor barométrico.', severity: 'medium' },
  'P0087': { title: 'Presión del Riel de Combustible Baja', desc: 'La presión en el riel común es menor a la esperada.', fix: 'Revisar bomba de alta presión, regulador, filtro y posibles fugas.', severity: 'high' },
  'P0088': { title: 'Presión del Riel de Combustible Alta', desc: 'La presión en el riel común es mayor a la especificada.', fix: 'Revisar regulador de presión, válvula de alivio y sensor de presión.', severity: 'high' },
  'P0089': { title: 'Rendimiento del Regulador de Presión de Combustible', desc: 'El regulador no mantiene la presión correcta.', fix: 'Reemplazar regulador de presión de combustible, verificar líneas.', severity: 'high' },
  'P0205': { title: 'Circuito del Inyector - Cilindro 5', desc: 'Falla en el circuito del inyector del cilindro 5.', fix: 'Revisar cableado, conector y resistencia del inyector 5.', severity: 'high' },
  'P0206': { title: 'Circuito del Inyector - Cilindro 6', desc: 'Falla en el circuito del inyector del cilindro 6.', fix: 'Revisar cableado, conector y resistencia del inyector 6.', severity: 'high' },
  'P0207': { title: 'Circuito del Inyector - Cilindro 7', desc: 'Falla en el circuito del inyector del cilindro 7.', fix: 'Revisar cableado, conector y resistencia del inyector 7.', severity: 'high' },
  'P0208': { title: 'Circuito del Inyector - Cilindro 8', desc: 'Falla en el circuito del inyector del cilindro 8.', fix: 'Revisar cableado, conector y resistencia del inyector 8.', severity: 'high' },
  'P0341': { title: 'Rango/Rendimiento del Sensor CMP', desc: 'El sensor del árbol de levas envía señal fuera de rango.', fix: 'Verificar sincronización de distribución, sensor CMP y cableado.', severity: 'high' },
  'P0345': { title: 'Circuito del Sensor CMP A (Banco 2)', desc: 'No se recibe señal del sensor del árbol de levas banco 2.', fix: 'Revisar sensor CMP banco 2, cableado y conector.', severity: 'high' },
  'P0351': { title: 'Bobina de Encendido A - Circuito Primario', desc: 'Falla en el circuito de la bobina de encendido del cilindro 1.', fix: 'Reemplazar bobina del cilindro 1, verificar cableado y conector.', severity: 'high' },
  'P0352': { title: 'Bobina de Encendido B - Circuito Primario', desc: 'Falla en el circuito de la bobina del cilindro 2.', fix: 'Reemplazar bobina del cilindro 2, verificar cableado.', severity: 'high' },
  'P0353': { title: 'Bobina de Encendido C - Circuito Primario', desc: 'Falla en el circuito de la bobina del cilindro 3.', fix: 'Reemplazar bobina del cilindro 3, verificar cableado.', severity: 'high' },
  'P0354': { title: 'Bobina de Encendido D - Circuito Primario', desc: 'Falla en el circuito de la bobina del cilindro 4.', fix: 'Reemplazar bobina del cilindro 4, verificar cableado.', severity: 'high' },
  'P0463': { title: 'Sensor de Nivel de Combustible - Entrada Alta', desc: 'Señal alta del sensor de nivel de combustible.', fix: 'Revisar cableado del sensor de nivel, posible circuito abierto.', severity: 'low' },
  'P0496': { title: 'Flujo de Purga EVAP Alto', desc: 'Flujo excesivo de purga del sistema EVAP detectado.', fix: 'Reemplazar válvula de purga EVAP (posiblemente atascada abierta).', severity: 'low' },
  'P0497': { title: 'Flujo de Purga EVAP Bajo', desc: 'Flujo insuficiente de purga del sistema EVAP.', fix: 'Revisar válvula de purga EVAP, mangueras y canister.', severity: 'low' },
  'P0501': { title: 'Rango/Rendimiento del Sensor de Velocidad', desc: 'El sensor de velocidad reporta valores inconsistentes.', fix: 'Verificar sensor VSS, cable del velocímetro y engranajes.', severity: 'medium' },
  'P0341': { title: 'Rango/Rendimiento del Sensor CMP', desc: 'Señal fuera de rango del sensor del árbol de levas.', fix: 'Verificar distribución, sensor CMP y cableado.', severity: 'high' },
};
