import { DtcEntry } from './obd2-database';

export const OBD2_DATABASE_P6: Record<string, DtcEntry> = {
  // === P08xx — Transmisión avanzada ===
  'P0800': { title: 'Circuito de Solicitud de Control de Caja de Transferencia', desc: 'Falla en la comunicación con la caja de transferencia (4x4).', fix: 'Revisar módulo de caja de transferencia, cableado y motor de transferencia.', severity: 'medium' },
  'P0805': { title: 'Circuito del Sensor de Posición del Embrague', desc: 'Falla en el sensor que detecta si el pedal de embrague está presionado.', fix: 'Revisar switch del embrague, cableado y conector.', severity: 'low' },
  'P0810': { title: 'Error de Control de Posición del Embrague', desc: 'El sistema de embrague automático no logra la posición correcta.', fix: 'Revisar actuador del embrague, sensor de posición y fluido hidráulico.', severity: 'high' },
  'P0826': { title: 'Circuito del Switch de Cambio Arriba/Abajo', desc: 'Falla en el circuito de los botones de cambio manual (tiptronic).', fix: 'Revisar switches de cambio en el volante o palanca, cableado.', severity: 'low' },
  'P0840': { title: 'Circuito del Sensor de Presión de Fluido de Transmisión A', desc: 'Falla en el sensor de presión del fluido de la transmisión.', fix: 'Revisar sensor de presión, cableado y nivel de fluido ATF.', severity: 'medium' },
  'P0868': { title: 'Presión de Fluido de Transmisión Baja', desc: 'La presión del fluido ATF es menor a la requerida.', fix: 'Verificar nivel de ATF, bomba de aceite de la transmisión y filtro.', severity: 'high' },
  'P0870': { title: 'Presión de Fluido de Transmisión Alta', desc: 'La presión del fluido ATF es mayor a la esperada.', fix: 'Revisar regulador de presión de línea y cuerpo de válvulas.', severity: 'medium' },
  'P0880': { title: 'Circuito de Alimentación del Módulo TCM', desc: 'Falla en la alimentación eléctrica del módulo de transmisión.', fix: 'Revisar fusible, relé y cableado de alimentación del TCM.', severity: 'high' },
  'P0900': { title: 'Circuito del Actuador del Embrague', desc: 'Falla en el circuito del actuador del embrague automático.', fix: 'Revisar actuador del embrague, cableado y conector.', severity: 'high' },
  'P0910': { title: 'Circuito del Actuador de Selección de Marcha', desc: 'Falla en el motor de selección de marcha (transmisión automatizada).', fix: 'Revisar actuador de selección, cableado y módulo TCM.', severity: 'high' },
  'P0920': { title: 'Circuito del Actuador de Avance de Marcha', desc: 'Falla en el actuador de engranaje de marcha.', fix: 'Revisar actuador de avance, cableado y módulo TCM.', severity: 'high' },
  // === Diésel — Inyección de combustible ===
  'P0251': { title: 'Bomba de Inyección A - Falla Mecánica (Diésel)', desc: 'Falla mecánica en la bomba de inyección de combustible diésel.', fix: 'Verificar bomba de inyección, sincronización y presión de combustible.', severity: 'high' },
  'P0252': { title: 'Bomba de Inyección A - Rango/Rendimiento (Diésel)', desc: 'La bomba de inyección no entrega el volumen correcto de combustible.', fix: 'Revisar bomba de inyección, regulador de presión y filtros.', severity: 'high' },
  'P0253': { title: 'Circuito del Inyector 1 (Diésel)', desc: 'Falla en el circuito del inyector diésel del cilindro 1.', fix: 'Revisar inyector, cableado y señal de excitación del ECM.', severity: 'high' },
  'P0254': { title: 'Inyector 1 - Circuito Alto (Diésel)', desc: 'Señal alta en el circuito del inyector diésel cilindro 1.', fix: 'Verificar cableado del inyector 1, posible cortocircuito.', severity: 'high' },
  'P0263': { title: 'Contribución/Balance del Cilindro 1 (Diésel)', desc: 'El cilindro 1 no contribuye correctamente a la potencia del motor.', fix: 'Revisar inyector, compresión y bujía de precalentamiento del cilindro 1.', severity: 'high' },
  'P0266': { title: 'Contribución/Balance del Cilindro 2 (Diésel)', desc: 'El cilindro 2 no contribuye correctamente a la potencia.', fix: 'Revisar inyector, compresión y bujía de precalentamiento del cilindro 2.', severity: 'high' },
  'P0269': { title: 'Contribución/Balance del Cilindro 3 (Diésel)', desc: 'El cilindro 3 no contribuye correctamente a la potencia.', fix: 'Revisar inyector, compresión y bujía de precalentamiento del cilindro 3.', severity: 'high' },
  'P0272': { title: 'Contribución/Balance del Cilindro 4 (Diésel)', desc: 'El cilindro 4 no contribuye correctamente a la potencia.', fix: 'Revisar inyector, compresión y bujía de precalentamiento del cilindro 4.', severity: 'high' },
  // === Diésel — Bujías de precalentamiento ===
  'P0380': { title: 'Circuito de Bujías de Precalentamiento (Glow Plugs)', desc: 'Falla general en el circuito del sistema de precalentamiento diésel.', fix: 'Revisar relé de bujías de precalentamiento, fusible y cableado.', severity: 'medium' },
  'P0381': { title: 'Indicador de Bujías de Precalentamiento', desc: 'Falla en el circuito del indicador de precalentamiento en tablero.', fix: 'Revisar bombillo indicador, cableado y módulo de precalentamiento.', severity: 'low' },
  'P0382': { title: 'Circuito de Bujías de Precalentamiento B', desc: 'Falla en el circuito secundario de precalentamiento.', fix: 'Revisar bujías de precalentamiento, relé y cableado individual.', severity: 'medium' },
  'P0670': { title: 'Módulo de Control de Bujías de Precalentamiento', desc: 'Falla en el módulo de control del sistema de precalentamiento.', fix: 'Reemplazar módulo de control de glow plugs, verificar alimentación.', severity: 'medium' },
  'P0671': { title: 'Circuito de Bujía de Precalentamiento - Cilindro 1', desc: 'Falla en la bujía de precalentamiento del cilindro 1.', fix: 'Medir resistencia de la bujía, reemplazar si está abierta o en corto.', severity: 'medium' },
  'P0672': { title: 'Circuito de Bujía de Precalentamiento - Cilindro 2', desc: 'Falla en la bujía de precalentamiento del cilindro 2.', fix: 'Medir resistencia de la bujía 2, reemplazar si es necesario.', severity: 'medium' },
  'P0673': { title: 'Circuito de Bujía de Precalentamiento - Cilindro 3', desc: 'Falla en la bujía de precalentamiento del cilindro 3.', fix: 'Medir resistencia de la bujía 3, reemplazar si es necesario.', severity: 'medium' },
  'P0674': { title: 'Circuito de Bujía de Precalentamiento - Cilindro 4', desc: 'Falla en la bujía de precalentamiento del cilindro 4.', fix: 'Medir resistencia de la bujía 4, reemplazar si es necesario.', severity: 'medium' },
  'P0675': { title: 'Circuito de Bujía de Precalentamiento - Cilindro 5', desc: 'Falla en la bujía de precalentamiento del cilindro 5.', fix: 'Medir resistencia de la bujía 5, reemplazar si es necesario.', severity: 'medium' },
  'P0676': { title: 'Circuito de Bujía de Precalentamiento - Cilindro 6', desc: 'Falla en la bujía de precalentamiento del cilindro 6.', fix: 'Medir resistencia de la bujía 6, reemplazar si es necesario.', severity: 'medium' },
  // === Diésel — DPF y SCR ===
  'P2003': { title: 'Eficiencia del Filtro de Partículas (DPF) Baja (B2)', desc: 'El DPF del banco 2 no filtra partículas correctamente.', fix: 'Regeneración forzada del DPF. Si falla, limpieza o reemplazo.', severity: 'medium' },
  'P2031': { title: 'Sensor de Temperatura del Gas de Escape (Banco 1)', desc: 'Señal fuera de rango del sensor EGT banco 1.', fix: 'Revisar sensor de temperatura de escape, cableado y conector.', severity: 'medium' },
  'P2032': { title: 'Sensor de Temperatura de Escape - Bajo (B1)', desc: 'Señal baja del sensor EGT banco 1.', fix: 'Verificar cableado del sensor EGT, posible corto a tierra.', severity: 'medium' },
  'P2033': { title: 'Sensor de Temperatura de Escape - Alto (B1)', desc: 'Señal alta del sensor EGT banco 1.', fix: 'Verificar cableado y sensor EGT, posible circuito abierto.', severity: 'medium' },
  'P2047': { title: 'Circuito del Inyector de Reductor (SCR) B1', desc: 'Falla en el inyector de AdBlue/DEF banco 1.', fix: 'Revisar inyector de urea, bomba AdBlue, cableado y nivel de DEF.', severity: 'medium' },
  'P2048': { title: 'Inyector de Reductor (SCR) - Bajo B1', desc: 'Señal baja en el circuito del inyector de AdBlue.', fix: 'Verificar cableado del inyector SCR, posible corto a tierra.', severity: 'medium' },
  'P204F': { title: 'Eficiencia del Sistema SCR de NOx', desc: 'El sistema de reducción catalítica selectiva no reduce NOx correctamente.', fix: 'Verificar calidad del AdBlue/DEF, inyector SCR y catalizador SCR.', severity: 'medium' },
  'P2458': { title: 'Tiempo de Regeneración del DPF', desc: 'La regeneración del filtro de partículas toma más tiempo del normal.', fix: 'Realizar regeneración estática. Verificar sensor de presión diferencial del DPF.', severity: 'medium' },
  'P2459': { title: 'Frecuencia de Regeneración del DPF', desc: 'Las regeneraciones del DPF ocurren con demasiada frecuencia.', fix: 'Revisar inyectores (posible exceso de hollín), sensor de presión del DPF.', severity: 'medium' },
  'P2463': { title: 'Acumulación Excesiva de Hollín en DPF', desc: 'El filtro de partículas tiene una acumulación de hollín por encima del límite.', fix: 'Realizar regeneración forzada. Si no funciona, limpieza profesional del DPF.', severity: 'high' },
  // === Más códigos de carrocería B ===
  'B0010': { title: 'Circuito del Airbag Lateral Izquierdo', desc: 'Falla en el circuito del airbag lateral del conductor.', fix: 'Revisar cableado del airbag lateral, conector y módulo SRS.', severity: 'high' },
  'B0011': { title: 'Circuito del Airbag Lateral Derecho', desc: 'Falla en el circuito del airbag lateral del pasajero.', fix: 'Revisar cableado del airbag lateral derecho y módulo SRS.', severity: 'high' },
  'B0020': { title: 'Circuito del Airbag de Cortina Izquierdo', desc: 'Falla en el circuito del airbag de cortina del lado del conductor.', fix: 'Revisar cableado de la cortina de aire, conectores y módulo SRS.', severity: 'high' },
  'B0021': { title: 'Circuito del Airbag de Cortina Derecho', desc: 'Falla en el circuito del airbag de cortina del lado del pasajero.', fix: 'Revisar cableado de la cortina de aire derecha y módulo SRS.', severity: 'high' },
  'B0050': { title: 'Sensor de Impacto Frontal Izquierdo', desc: 'Falla en el sensor de impacto frontal del lado del conductor.', fix: 'Revisar sensor de impacto, cableado y conector.', severity: 'high' },
  'B0051': { title: 'Sensor de Impacto Frontal Derecho', desc: 'Falla en el sensor de impacto frontal del lado del pasajero.', fix: 'Revisar sensor de impacto derecho, cableado y conector.', severity: 'high' },
  'B0060': { title: 'Sensor de Impacto Lateral Izquierdo', desc: 'Falla en el sensor de impacto lateral del conductor.', fix: 'Revisar sensor de impacto lateral, cableado y módulo SRS.', severity: 'high' },
  'B0100': { title: 'Voltaje de Alimentación del Módulo SRS', desc: 'Voltaje fuera de rango en el módulo de airbags.', fix: 'Verificar batería, cableado de alimentación del módulo SRS y tierras.', severity: 'high' },
  // === Más chasis C ===
  'C0060': { title: 'Circuito del Motor de la Bomba ABS', desc: 'Falla en el motor de la bomba del sistema de frenos ABS.', fix: 'Revisar relé de la bomba ABS, motor de bomba, fusible y cableado.', severity: 'high' },
  'C0065': { title: 'Relé de la Bomba ABS', desc: 'Falla en el relé que controla la bomba del ABS.', fix: 'Reemplazar relé de la bomba ABS, verificar cableado.', severity: 'high' },
  'C0070': { title: 'Válvula Solenoide de Freno ABS', desc: 'Falla en una de las válvulas solenoides del módulo ABS.', fix: 'Posible reemplazo del módulo hidráulico ABS completo.', severity: 'high' },
  'C0110': { title: 'Circuito del Motor de la Bomba de Control de Estabilidad', desc: 'Falla en el motor de la bomba del sistema ESP/ESC.', fix: 'Revisar motor de bomba ESP, relé, fusible y cableado.', severity: 'high' },
  'C0300': { title: 'Sensor del Ángulo de Dirección', desc: 'Mal funcionamiento del sensor de ángulo del volante.', fix: 'Calibrar sensor de ángulo de dirección con escáner. Reemplazar si falla.', severity: 'medium' },
  'C0455': { title: 'Sensor de Velocidad de Giro (Yaw Rate)', desc: 'Falla en el sensor de velocidad de giro del sistema ESP.', fix: 'Revisar sensor de giro, cableado y calibración del módulo ESP.', severity: 'medium' },
  'C0460': { title: 'Sensor de Aceleración Lateral', desc: 'Falla en el sensor de aceleración lateral del sistema de estabilidad.', fix: 'Revisar sensor de aceleración lateral, cableado y módulo ESP.', severity: 'medium' },
  'C0561': { title: 'Sistema de Control de Estabilidad Deshabilitado', desc: 'El sistema ESP/ESC se ha deshabilitado por una falla detectada.', fix: 'Diagnosticar código primario que causó la desactivación del ESP.', severity: 'medium' },
  'C0710': { title: 'Circuito del Sensor de Dirección Asistida Eléctrica', desc: 'Falla en el sistema de dirección asistida eléctrica (EPS).', fix: 'Revisar motor EPS, sensor de torque, cableado y módulo de control.', severity: 'high' },
  'C0800': { title: 'Voltaje del Sistema de Frenos de Potencia', desc: 'Voltaje fuera de rango en el sistema de frenos eléctricos.', fix: 'Verificar batería, alternador y cableado del módulo de frenos.', severity: 'high' },
};
