package com.elysium369.meet.core.services

/**
 * Data-driven service ontology shared by physical, digital and hybrid work.
 * A custom entry is always available so the network can accept legitimate
 * needs without pretending that a hard-coded list represents every trade.
 */
data class UniversalServiceDefinition(
    val id: String,
    val domain: String,
    val name: String,
    val modalities: Set<UniversalServiceModality>,
    val icon: String,
    val riskTier: String = "STANDARD",
    val commonTasks: List<String> = emptyList(),
    val defaultEstimatedPriceCrc: Double = 15000.0,
    val requiresDestination: Boolean = false,
    val adminRoleName: String = "Especialista Certificado",
    val adminDescription: String = "Despacho de servicios y gestión de solicitudes en tiempo real.",
)

enum class UniversalServiceModality(val label: String) {
    PHYSICAL("A domicilio"),
    DIGITAL("Remoto / digital"),
    HYBRID("Híbrido"),
}

object UniversalServiceCatalog {
    private val allModalities = UniversalServiceModality.entries.toSet()

    val definitions = listOf(
        UniversalServiceDefinition(
            id = "hardware_materials",
            domain = "Ferretería & Materiales",
            name = "Ferretería y Materiales (Tubos, Grifería, Cables)",
            modalities = physical(),
            icon = "🔩",
            riskTier = "STANDARD",
            commonTasks = listOf("Tubos PVC 1/2\"", "Grifería y llaves de paso", "Cables THHN #12", "Breakers y cajas térmicas", "Cemento y adhesivos", "Pintura y selladores", "Tornillería y fijación"),
            defaultEstimatedPriceCrc = 15000.0,
            requiresDestination = false,
            adminRoleName = "Ferretería Afiliada",
            adminDescription = "Venta y despacho de materiales con cotización en subasta dual para clientes e instaladores.",
        ),
        UniversalServiceDefinition(
            id = "hardware_plumbing_install",
            domain = "Ferretería & Materiales",
            name = "Plomería: Tubos, Válvulas e Instalación",
            modalities = physical(),
            icon = "🚰",
            riskTier = "STANDARD",
            commonTasks = listOf("Fuga de agua en tubería", "Instalación de grifería y mezcladoras", "Reparación de inodoro y tanque", "Desobstrucción de drenajes", "Instalación de tubería PVC", "Instalación de bomba de agua"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Plomero Especialista",
            adminDescription = "Órdenes de plomería a domicilio, instalación de materiales y cobro seguro con Escrow.",
        ),
        UniversalServiceDefinition(
            id = "hardware_electrical_install",
            domain = "Ferretería & Materiales",
            name = "Electricidad: Cableado, Breakers e Instalación",
            modalities = physical(),
            icon = "⚡",
            riskTier = "ELEVATED",
            commonTasks = listOf("Cortocircuito urgente", "Cambio de breaker que se cae", "Acometida 110V/220V", "Cableado de residencia", "Instalación de lámparas y tomacorrientes", "Balanceo de cargas"),
            defaultEstimatedPriceCrc = 25000.0,
            requiresDestination = false,
            adminRoleName = "Técnico Electricista",
            adminDescription = "Atención de averías eléctricas residenciales y comerciales con verificación de seguridad.",
        ),
        UniversalServiceDefinition(
            id = "hardware_locksmith",
            domain = "Ferretería & Materiales",
            name = "Cerrajería: Cerraduras, Cilindros e Instalación",
            modalities = physical(),
            icon = "🔐",
            riskTier = "STANDARD",
            commonTasks = listOf("Apertura de puerta trabada", "Cambio de llavín o cilindro", "Instalación de cerradura digital", "Copia de llave de seguridad", "Reparación de cerrojo"),
            defaultEstimatedPriceCrc = 18000.0,
            requiresDestination = false,
            adminRoleName = "Cerrajero Profesional",
            adminDescription = "Despacho de emergencias de cerrajería para residencias, comercios y vehículos.",
        ),
        UniversalServiceDefinition(
            id = "hardware_construction",
            domain = "Ferretería & Materiales",
            name = "Construcción: Cemento, Fijación y Mano de Obra",
            modalities = physical(),
            icon = "🧱",
            riskTier = "STANDARD",
            commonTasks = listOf("Repello y afinado", "Pegado de bloques y ladrillos", "Reparación de fisuras y goteras", "Instalación de piso y azulejo", "Muro perimetral", "Fundición y viguetas"),
            defaultEstimatedPriceCrc = 35000.0,
            requiresDestination = false,
            adminRoleName = "Maestro de Obras / Albañil",
            adminDescription = "Gestión de obras, cotización por metro o jornada y provisión de cemento y agregados.",
        ),
        UniversalServiceDefinition(
            id = "home_cleaning",
            domain = "Hogar",
            name = "Limpieza residencial y comercial",
            modalities = physical(),
            icon = "🧹",
            riskTier = "STANDARD",
            commonTasks = listOf("Limpieza profunda de hogar", "Limpieza estándar por horas", "Lavado de sillones y alfombras", "Limpieza post-construcción", "Desinfección de baños y cocina", "Lavado de ventanas"),
            defaultEstimatedPriceCrc = 18000.0,
            requiresDestination = false,
            adminRoleName = "Profesional de Limpieza",
            adminDescription = "Servicios de aseo y mantenimiento de espacios con garantía de satisfacción.",
        ),
        UniversalServiceDefinition(
            id = "plumbing",
            domain = "Hogar",
            name = "Plomería",
            modalities = physical(),
            icon = "🚰",
            riskTier = "STANDARD",
            commonTasks = listOf("Fuga en tubería", "Instalación de grifería", "Inodoro averiado", "Desagüe obstruido", "Bomba de agua / Tanque", "Calentador de agua"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Plomero Residencial",
            adminDescription = "Atención rápida de fugas e instalaciones hidrosanitarias a domicilio.",
        ),
        UniversalServiceDefinition(
            id = "electrical_home",
            domain = "Hogar",
            name = "Electricidad residencial",
            modalities = physical(),
            icon = "⚡",
            riskTier = "ELEVATED",
            commonTasks = listOf("Diagnóstico de corto", "Cambio de térmicos", "Tomacorrientes e interruptores", "Lámparas y ventiladores", "Revisión de panel eléctrico"),
            defaultEstimatedPriceCrc = 25000.0,
            requiresDestination = false,
            adminRoleName = "Electricista Certificado",
            adminDescription = "Diagnóstico e instalación de redes eléctricas residenciales con protección integral.",
        ),
        UniversalServiceDefinition(
            id = "painting",
            domain = "Hogar",
            name = "Pintura y acabados",
            modalities = physical(),
            icon = "🎨",
            riskTier = "STANDARD",
            commonTasks = listOf("Pintura interior de paredes", "Pintura exterior y fachada", "Tratamiento de humedad / sellado", "Pintura de rejas y portones", "Barnizado de madera"),
            defaultEstimatedPriceCrc = 30000.0,
            requiresDestination = false,
            adminRoleName = "Pintor Profesional",
            adminDescription = "Presupuestos de pintura por metro cuadrado con preparación de superficies.",
        ),
        UniversalServiceDefinition(
            id = "carpentry",
            domain = "Hogar",
            name = "Carpintería",
            modalities = physical(),
            icon = "🪚",
            riskTier = "STANDARD",
            commonTasks = listOf("Reparación de puertas y muebles", "Fabricación de closets / muebles a medida", "Instalación de rodapiés", "Reparación de gavetas y bisagras", "Estructuras de madera"),
            defaultEstimatedPriceCrc = 25000.0,
            requiresDestination = false,
            adminRoleName = "Carpintero Calificado",
            adminDescription = "Fabricación y restauración de mobiliario con cotizaciones a medida.",
        ),
        UniversalServiceDefinition(
            id = "gardening",
            domain = "Hogar",
            name = "Jardinería y áreas verdes",
            modalities = physical(),
            icon = "🌿",
            riskTier = "STANDARD",
            commonTasks = listOf("Corte de zacate / césped", "Poda de árboles y setos", "Diseño de jardín", "Abonado y fumigación", "Limpieza de maleza"),
            defaultEstimatedPriceCrc = 15000.0,
            requiresDestination = false,
            adminRoleName = "Jardinero y Paisajista",
            adminDescription = "Mantenimiento periódico y embellecimiento de áreas verdes.",
        ),
        UniversalServiceDefinition(
            id = "appliance_repair",
            domain = "Hogar",
            name = "Reparación de electrodomésticos",
            modalities = physical(),
            icon = "🔧",
            riskTier = "STANDARD",
            commonTasks = listOf("Revisión de refrigeradora / nevera", "Reparación de lavadora / secadora", "Microondas averiado", "Cocina eléctrica o de inducción", "Aire acondicionado"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Técnico de Línea Blanca",
            adminDescription = "Diagnóstico y cambio de repuestos para electrodomésticos del hogar.",
        ),
        UniversalServiceDefinition(
            id = "moving",
            domain = "Logística",
            name = "Mudanzas y carga",
            modalities = physical(),
            icon = "📦",
            riskTier = "STANDARD",
            commonTasks = listOf("Mudanza completa de casa/apartamento", "Transporte de muebles y electrodomésticos", "Flete local en camión/pickup", "Carga pesada y descarga", "Servicio de embalaje"),
            defaultEstimatedPriceCrc = 35000.0,
            requiresDestination = true,
            adminRoleName = "Transportista de Carga",
            adminDescription = "Traslado seguro de pertenencias con origen y destino en mapa satelital.",
        ),
        UniversalServiceDefinition(
            id = "courier",
            domain = "Logística",
            name = "Mensajería y entregas express",
            modalities = physical(),
            icon = "🛵",
            riskTier = "STANDARD",
            commonTasks = listOf("Envío express de documentos", "Entrega de paquetes y pedidos", "Compras y mandados urgentes", "Trámites bancarios y firmas"),
            defaultEstimatedPriceCrc = 4000.0,
            requiresDestination = true,
            adminRoleName = "Mensajero / Repartidor Express",
            adminDescription = "Entregas punto a punto con seguimiento GPS en tiempo real.",
        ),
        UniversalServiceDefinition(
            id = "personal_transport",
            domain = "Movilidad",
            name = "Transporte de personas",
            modalities = physical(),
            icon = "🚘",
            riskTier = "ELEVATED",
            commonTasks = listOf("Viaje local", "Viaje al aeropuerto", "Viaje interurbano", "Viaje con paradas múltiples", "Viaje de encomienda"),
            defaultEstimatedPriceCrc = 5000.0,
            requiresDestination = true,
            adminRoleName = "Conductor / Chofer MEET",
            adminDescription = "Despacho de viajes con tarifa justa, subasta en tiempo real y protección de seguridad.",
        ),
        UniversalServiceDefinition(
            id = "roadside",
            domain = "Movilidad",
            name = "Grúa y Asistencia Vial de Emergencia",
            modalities = physical(),
            icon = "🚛",
            riskTier = "ELEVATED",
            commonTasks = listOf("Arrastre a taller o residencia", "Grúa de plataforma hidráulica", "Cambio de llanta pinchada", "Paso de corriente / batería muerta", "Suministro de combustible", "Extracción en cuneta o fosa"),
            defaultEstimatedPriceCrc = 30000.0,
            requiresDestination = true,
            adminRoleName = "Operador de Grúa / Auxilio Vial",
            adminDescription = "Recepción de emergencias mecánicas y viales con navegación directa y cobro garantizado.",
        ),
        UniversalServiceDefinition(
            id = "mechanical",
            domain = "Automotriz",
            name = "Mecánica Automotriz y Diagnóstico a Domicilio",
            modalities = physical(),
            icon = "🛠️",
            riskTier = "ELEVATED",
            commonTasks = listOf("Diagnóstico con escáner OBD / DTC", "Frenos: cambio de pastillas y discos", "Cambio de aceite, filtro y bujías", "Vehículo no enciende / arranque", "Suspensión, amortiguadores y rótulas", "Revisión pre-compra completa"),
            defaultEstimatedPriceCrc = 25000.0,
            requiresDestination = false,
            adminRoleName = "Mecánico Automotriz Certificado",
            adminDescription = "Servicio mecánico profesional a domicilio o en taller con lectura de códigos de falla.",
        ),
        UniversalServiceDefinition(
            id = "auto_parts",
            domain = "Automotriz",
            name = "Repuestos y Autopartes (VIN / OEM / Compatibilidad)",
            modalities = physical(),
            icon = "⚙️",
            riskTier = "STANDARD",
            commonTasks = listOf("Pastillas y discos de freno", "Amortiguadores delanteros/traseros", "Batería 12V con instalación", "Radiador y refrigerante", "Filtros de aire, aceite y cabina", "Sensores de motor (O2, MAF, CKP)", "Bomba de agua / termostato"),
            defaultEstimatedPriceCrc = 25000.0,
            requiresDestination = true,
            adminRoleName = "Distribuidor / Repuestera",
            adminDescription = "Cotización y subasta de repuestos garantizados con compatibilidad por chasis/VIN.",
        ),
        UniversalServiceDefinition(
            id = "vehicle_detailing",
            domain = "Automotriz",
            name = "Lavado, Pulido y Detailing Automotriz",
            modalities = physical(),
            icon = "✨",
            riskTier = "STANDARD",
            commonTasks = listOf("Lavado completo a domicilio", "Pulido y encerado de pintura", "Lavado profundo de tapicería", "Restauración de focos y silvines", "Desinfección con ozono"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Especialista en Detailing",
            adminDescription = "Cuidado estético y embellecimiento vehicular a domicilio.",
        ),
        UniversalServiceDefinition(
            id = "pet_care",
            domain = "Cuidado",
            name = "Cuidado de mascotas y paseo",
            modalities = physical(),
            icon = "🐾",
            riskTier = "STANDARD",
            commonTasks = listOf("Paseo canino", "Hospedaje / guardería", "Baño y corte a domicilio", "Alimentación y visitas", "Entrenamiento básico"),
            defaultEstimatedPriceCrc = 10000.0,
            requiresDestination = false,
            adminRoleName = "Cuidador / Paseador de Mascotas",
            adminDescription = "Atención cariñosa y responsable para animales de compañía.",
        ),
        UniversalServiceDefinition(
            id = "elder_support",
            domain = "Cuidado",
            name = "Acompañamiento de adultos mayores",
            modalities = physical(),
            icon = "🤝",
            riskTier = "ELEVATED",
            commonTasks = listOf("Acompañamiento diurno", "Recordatorio de medicamentos", "Asistencia en citas médicas", "Paseos y estimulación cognitiva"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Acompañante de Adultos Mayores",
            adminDescription = "Cuidado compasivo y profesional para adultos mayores con validación de identidad.",
        ),
        UniversalServiceDefinition(
            id = "childcare",
            domain = "Cuidado",
            name = "Cuidado infantil",
            modalities = physical(),
            icon = "🧸",
            riskTier = "RESTRICTED",
            commonTasks = listOf("Niñera por horas", "Cuidado diurno en casa", "Apoyo con tareas escolares", "Actividades recreativas"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Cuidador Infantil Acreditado",
            adminDescription = "Cuidado infantil con verificación documental rigurosa de antecedentes.",
        ),
        UniversalServiceDefinition(
            id = "beauty",
            domain = "Bienestar",
            name = "Belleza, barbería y estética",
            modalities = physical(),
            icon = "✂️",
            riskTier = "STANDARD",
            commonTasks = listOf("Corte de cabello hombre/mujer", "Barbería y perfilado", "Manicure y pedicure", "Maquillaje y peinado para evento", "Depilación"),
            defaultEstimatedPriceCrc = 15000.0,
            requiresDestination = false,
            adminRoleName = "Estilista / Barbero Profesional",
            adminDescription = "Servicios estéticos a domicilio con estándares profesionales de higiene.",
        ),
        UniversalServiceDefinition(
            id = "fitness",
            domain = "Bienestar",
            name = "Entrenamiento personal y salud",
            modalities = hybrid(),
            icon = "🏋️",
            riskTier = "STANDARD",
            commonTasks = listOf("Entrenamiento funcional a domicilio", "Clases de yoga / pilates", "Plan de acondicionamiento físico", "Asesoría deportiva"),
            defaultEstimatedPriceCrc = 18000.0,
            requiresDestination = false,
            adminRoleName = "Entrenador Personal Certificado",
            adminDescription = "Planes de ejercicio adaptados y sesiones de entrenamiento presenciales o virtuales.",
        ),
        UniversalServiceDefinition(
            id = "tutoring",
            domain = "Educación",
            name = "Tutorías y clases particulares",
            modalities = hybrid(),
            icon = "📚",
            riskTier = "STANDARD",
            commonTasks = listOf("Matemáticas y física", "Idiomas (Inglés, Francés)", "Español y redacción", "Química y biología", "Música (Guitarra, Piano)"),
            defaultEstimatedPriceCrc = 12000.0,
            requiresDestination = false,
            adminRoleName = "Profesor / Tutor Académico",
            adminDescription = "Refuerzo escolar y universitario con modalidades presenciales y remotas.",
        ),
        UniversalServiceDefinition(
            id = "translation",
            domain = "Profesional",
            name = "Traducción oficial y comercial",
            modalities = digital(),
            icon = "🌐",
            riskTier = "STANDARD",
            commonTasks = listOf("Traducción técnica", "Traducción legal / jurada", "Revisión de estilo y corrección", "Subtitulado"),
            defaultEstimatedPriceCrc = 15000.0,
            requiresDestination = false,
            adminRoleName = "Traductor Profesional",
            adminDescription = "Traducción experta de documentos con entrega digital certificada.",
        ),
        UniversalServiceDefinition(
            id = "accounting",
            domain = "Profesional",
            name = "Contabilidad y tributación",
            modalities = digital(),
            icon = "🧾",
            riskTier = "ELEVATED",
            commonTasks = listOf("Declaración de impuestos D-104", "Facturación electrónica", "Estados financieros", "Cálculo de planillas y CCSS", "Asesoría fiscal"),
            defaultEstimatedPriceCrc = 25000.0,
            requiresDestination = false,
            adminRoleName = "Contador Público / Privado",
            adminDescription = "Servicios contables y declaraciones tributarias para personas y empresas.",
        ),
        UniversalServiceDefinition(
            id = "legal",
            domain = "Profesional",
            name = "Orientación legal y trámites",
            modalities = hybrid(),
            icon = "⚖️",
            riskTier = "RESTRICTED",
            commonTasks = listOf("Contratos de arrendamiento / servicios", "Trámites notariales y poderes", "Asesoría laboral", "Constitución de sociedades", "Asuntos de familia"),
            defaultEstimatedPriceCrc = 35000.0,
            requiresDestination = false,
            adminRoleName = "Abogado y Notario",
            adminDescription = "Asesoría jurídica y redacción de instrumentos legales con validez.",
        ),
        UniversalServiceDefinition(
            id = "graphic_design",
            domain = "Digital",
            name = "Diseño gráfico y branding",
            modalities = digital(),
            icon = "🖌️",
            riskTier = "STANDARD",
            commonTasks = listOf("Diseño de logotipo e identidad", "Material para redes sociales", "Diseño de empaques y etiquetas", "Brochures y catálogos", "Edición y retoque digital"),
            defaultEstimatedPriceCrc = 20000.0,
            requiresDestination = false,
            adminRoleName = "Diseñador Gráfico",
            adminDescription = "Creación visual y diseño de marca con entrega de archivos editables.",
        ),
        UniversalServiceDefinition(
            id = "software",
            domain = "Digital",
            name = "Software y automatización",
            modalities = digital(),
            icon = "💻",
            riskTier = "STANDARD",
            commonTasks = listOf("Desarrollo de páginas web", "Automatización de procesos (APIs)", "Desarrollo de aplicaciones móviles", "Bases de datos y dashboards"),
            defaultEstimatedPriceCrc = 45000.0,
            requiresDestination = false,
            adminRoleName = "Ingeniero de Software",
            adminDescription = "Soluciones tecnológicas y desarrollo a medida con código limpio.",
        ),
        UniversalServiceDefinition(
            id = "it_support",
            domain = "Digital",
            name = "Soporte técnico y redes",
            modalities = hybrid(),
            icon = "🛰️",
            riskTier = "STANDARD",
            commonTasks = listOf("Formateo e instalación de Windows/Mac", "Eliminación de virus y malware", "Configuración de redes Wi-Fi / routers", "Recuperación de datos", "Mantenimiento de computadoras"),
            defaultEstimatedPriceCrc = 18000.0,
            requiresDestination = false,
            adminRoleName = "Técnico en Informática",
            adminDescription = "Soporte presencial o remoto para equipos de cómputo y redes locales.",
        ),
        UniversalServiceDefinition(
            id = "photo_video",
            domain = "Creativo",
            name = "Fotografía y producción audiovisual",
            modalities = hybrid(),
            icon = "📸",
            riskTier = "STANDARD",
            commonTasks = listOf("Sesión de fotos familiar / retrato", "Fotografía de productos para catálogo", "Cobertura de eventos", "Grabación y edición de video", "Tomas con drone"),
            defaultEstimatedPriceCrc = 35000.0,
            requiresDestination = false,
            adminRoleName = "Fotógrafo / Videógrafo",
            adminDescription = "Producción audiovisual profesional con entrega digital en alta resolución.",
        ),
        UniversalServiceDefinition(
            id = "events",
            domain = "Eventos",
            name = "Producción de eventos y fiestas",
            modalities = physical(),
            icon = "🎪",
            riskTier = "STANDARD",
            commonTasks = listOf("Sonido e iluminación", "Animación y DJ", "Decoración temática", "Mobiliario y toldos", "Organización integral"),
            defaultEstimatedPriceCrc = 50000.0,
            requiresDestination = false,
            adminRoleName = "Organizador de Eventos",
            adminDescription = "Coordinación y equipamiento para eventos sociales y corporativos.",
        ),
        UniversalServiceDefinition(
            id = "food",
            domain = "Alimentos",
            name = "Comida y catering para eventos",
            modalities = physical(),
            icon = "🍽️",
            riskTier = "ELEVATED",
            commonTasks = listOf("Catering para reuniones", "Chef privado a domicilio", "Boquitas y repostería", "Parrillada y asados", "Pastelería personalizada"),
            defaultEstimatedPriceCrc = 40000.0,
            requiresDestination = false,
            adminRoleName = "Chef / Servicio de Catering",
            adminDescription = "Experiencias gastronómicas y catering con manipuladores de alimentos al día.",
        ),
        UniversalServiceDefinition(
            id = "security",
            domain = "Seguridad",
            name = "Seguridad privada y vigilancia",
            modalities = physical(),
            icon = "🛡️",
            riskTier = "RESTRICTED",
            commonTasks = listOf("Instalación de cámaras de seguridad (CCTV)", "Instalación de alarmas y sensores", "Vigilancia para eventos", "Cercas eléctricas"),
            defaultEstimatedPriceCrc = 35000.0,
            requiresDestination = false,
            adminRoleName = "Técnico / Oficial de Seguridad",
            adminDescription = "Sistemas de protección física y electrónica con certificación legal.",
        ),
        UniversalServiceDefinition(
            id = "custom",
            domain = "Otros",
            name = "Otro servicio especializado",
            modalities = allModalities,
            icon = "✦",
            riskTier = "STANDARD",
            commonTasks = listOf("Servicio a medida", "Consultoría específica", "Mantenimiento general", "Cotización personalizada"),
            defaultEstimatedPriceCrc = 15000.0,
            requiresDestination = false,
            adminRoleName = "Especialista Independiente",
            adminDescription = "Cotización y ejecución de labores especializadas en la red Elysium.",
        ),
    )

    fun search(query: String): List<UniversalServiceDefinition> {
        val normalized = query.trim().lowercase()
        if (normalized.isBlank()) return definitions
        return definitions.filter {
            it.name.lowercase().contains(normalized) ||
                it.domain.lowercase().contains(normalized)
        }
    }

    fun domains(): List<String> = definitions.map(UniversalServiceDefinition::domain).distinct()

    fun getById(id: String): UniversalServiceDefinition? = definitions.firstOrNull { it.id == id }

    private fun physical() = setOf(UniversalServiceModality.PHYSICAL)
    private fun digital() = setOf(UniversalServiceModality.DIGITAL)
    private fun hybrid() = allModalities
}

