package com.elysium369.meet.ai.domain

enum class AiFeature {
    DIAGNOSTIC_DTC,
    LIVE_PID_ANALYSIS,
    AI_COPILOT,
    REPAIR_GUIDE,
    VISUAL_3D_PART_CONTEXT,
    REPORT_PRE_SCAN,
    REPORT_POST_SCAN,
    DVIR,
    PREDICTIVE_HEALTH,
    OSCILLOSCOPE_ANALYSIS,
    TERMINAL_EXPLAINER,
    LIVE_LINK_REMOTE_ASSIST,
    MECHANIC_MARKETPLACE,
    GAUGE_MARKET,
    MANUAL_CENTER
}
