begin;
-- Preserve the existing Android catalogue in the authoritative unified experience.
insert into public.service_definitions(id,domain,display_name,supported_modalities,risk_tier) values
('pulperia_groceries','Pulperías & Minisúper','Pulpería Express: Abarrotes, Panadería y Bebidas',array['PHYSICAL'],'STANDARD'),
('soda_traditional_food','Sodas & Restaurantes','Soda Tradicional: Casados, Desayunos y Comida Típica',array['PHYSICAL'],'STANDARD'),
('hardware_materials','Ferretería & Materiales','Ferretería y Materiales (Tubos, Grifería, Cables)',array['PHYSICAL'],'STANDARD'),
('hardware_plumbing_install','Ferretería & Materiales','Plomería: Tubos, Válvulas e Instalación',array['PHYSICAL'],'STANDARD'),
('hardware_electrical_install','Ferretería & Materiales','Electricidad: Cableado, Breakers e Instalación',array['PHYSICAL'],'ELEVATED'),
('hardware_locksmith','Ferretería & Materiales','Cerrajería: Cerraduras, Cilindros e Instalación',array['PHYSICAL'],'STANDARD'),
('hardware_construction','Ferretería & Materiales','Construcción: Cemento, Fijación y Mano de Obra',array['PHYSICAL'],'STANDARD'),
('home_cleaning','Hogar','Limpieza residencial y comercial',array['PHYSICAL'],'STANDARD'),
('plumbing','Hogar','Plomería',array['PHYSICAL'],'STANDARD'),
('electrical_home','Hogar','Electricidad residencial',array['PHYSICAL'],'ELEVATED'),
('painting','Hogar','Pintura y acabados',array['PHYSICAL'],'STANDARD'),
('carpentry','Hogar','Carpintería',array['PHYSICAL'],'STANDARD'),
('gardening','Hogar','Jardinería y áreas verdes',array['PHYSICAL'],'STANDARD'),
('appliance_repair','Hogar','Reparación de electrodomésticos',array['PHYSICAL'],'STANDARD'),
('moving','Logística','Mudanzas y carga',array['PHYSICAL'],'STANDARD'),
('courier','Logística','Mensajería y entregas express',array['PHYSICAL'],'STANDARD'),
('personal_transport','Movilidad','Transporte de personas',array['PHYSICAL'],'ELEVATED'),
('roadside','Movilidad','Grúa y Asistencia Vial de Emergencia',array['PHYSICAL'],'ELEVATED'),
('mechanical','Automotriz','Mecánica Automotriz y Diagnóstico a Domicilio',array['PHYSICAL'],'ELEVATED'),
('auto_parts','Automotriz','Repuestos y Autopartes (VIN / OEM / Compatibilidad)',array['PHYSICAL'],'STANDARD'),
('vehicle_detailing','Automotriz','Lavado, Pulido y Detailing Automotriz',array['PHYSICAL'],'STANDARD'),
('pet_care','Cuidado','Cuidado de mascotas y paseo',array['PHYSICAL'],'STANDARD'),
('elder_support','Cuidado','Acompañamiento de adultos mayores',array['PHYSICAL'],'ELEVATED'),
('childcare','Cuidado','Cuidado infantil',array['PHYSICAL'],'RESTRICTED'),
('beauty','Bienestar','Belleza, barbería y estética',array['PHYSICAL'],'STANDARD'),
('fitness','Bienestar','Entrenamiento personal y salud',array['HYBRID'],'STANDARD'),
('tutoring','Educación','Tutorías y clases particulares',array['HYBRID'],'STANDARD'),
('translation','Profesional','Traducción oficial y comercial',array['DIGITAL'],'STANDARD'),
('accounting','Profesional','Contabilidad y tributación',array['DIGITAL'],'ELEVATED'),
('legal','Profesional','Orientación legal y trámites',array['HYBRID'],'RESTRICTED'),
('graphic_design','Digital','Diseño gráfico y branding',array['DIGITAL'],'STANDARD'),
('software','Digital','Software y automatización',array['DIGITAL'],'STANDARD'),
('it_support','Digital','Soporte técnico y redes',array['HYBRID'],'STANDARD'),
('photo_video','Creativo','Fotografía y producción audiovisual',array['HYBRID'],'STANDARD'),
('events','Eventos','Producción de eventos y fiestas',array['PHYSICAL'],'STANDARD'),
('food','Alimentos','Comida y catering para eventos',array['PHYSICAL'],'ELEVATED'),
('security','Seguridad','Seguridad privada y vigilancia',array['PHYSICAL'],'RESTRICTED'),
('custom','Otros','Otro servicio especializado',array['PHYSICAL','DIGITAL','HYBRID'],'STANDARD')
on conflict(id) do nothing;
commit;
